### ISSUE TITLE
C# Attribute square bracket notation not recognized

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#1]
_From @dimhotepus on December 5, 2014 9:39_

As you can see, right square bracket after NotNull attribute is italic, but should be normal, as a left
square bracket.

Stable Channel, Build 3065
Windows 8.1

![image](https://cloud.githubusercontent.com/assets/1983411/5313715/b9072e28-7c7c-11e4-8d95-82e8b9fd360e.png)

_Copied from original issue: SublimeTextBugs/Issues#598_

**Comment by wbond** [comment]
This was fixed as of dev build 3100.
