### ISSUE TITLE
html highlighting with numbers in attribute names

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#10]
_From @lope on October 2, 2014 16:23_

**Example**
`<body data-foo1bar='blah'></body>`

**Expected behavior:** data-foo1bar is highlighted green (meaning it's an attribute name)
**Current buggy behavior:** data-foo is highlighted green (attribute name) and 1bar is highlighted white, meaning it's seen as page content.

**Standards**
According to the HTML standard, only capital letters are not allowed in data-attribute names.
https://html.spec.whatwg.org/multipage/dom.html#attr-data-*

**Real world**
Numbers are accepted in html data attribute names. I've tested in Chrome and FF.
document.body.dataset finds and can use the attrubutes as expected.

_Copied from original issue: SublimeTextBugs/Issues#508_

**Comment by FichteFoll** [comment]
Can not reproduce; probably fixed on 3087.
