### ISSUE TITLE
JavaScript syntax highlighting: no space between `function` and parens breaks argument highlighting

### ISSUE THREAD

**Issue by MattDMo** [SublimeTextIssues/DefaultPackages#100]
This is an issue in both ST2 and ST3. Take the following code:

```javascript
arr.forEach(function(arg1) { return arg1; })
arr.forEach(function (arg1) { return arg1; })
play = function(arg) { return arg; }
function foo(arg1, arg2) { return arg1 + arg2; }

bar = {
    baz: function(args) {}
}
```
In `arr.forEach(function(arg1) { return arg1; })`, `arg1` is not scoped as `variable.parameter.function.js`, whereas in `arr.forEach(function (arg1) { return arg1; })` (note space between `function` and opening paren) it is highlighted appropriately. Other types of functions work fine:

![js_args_1](https://cloud.githubusercontent.com/assets/1776358/6047214/49806158-ac76-11e4-8e6f-714ed77e0bdc.png)

The problem is on line 260 of `JavaScript.tmLanguage`:

```xml
<string>\b(function)\s+([a-zA-Z_$]\w*)?\s*(\()(.*?)(\))</string>
<!--                  ^                           -->
```
`\s+` is matching one or more whitespace characters after `function`, where it should be zero or more - `\s*`. With that one change, everything works fine:

![js_args_2](https://cloud.githubusercontent.com/assets/1776358/6047306/dcd2df1c-ac76-11e4-90cd-ad8ad20b40e6.png)

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
