### ISSUE TITLE
Ruby syntax highlighting thinks `"` in regex begins a string

### ISSUE THREAD

**Issue by marnen** [SublimeTextIssues/DefaultPackages#102]
Example:
```ruby
string =~ /no quotes: [^"]*/
```

...the rest of the file after the `"` in the regex is highlighted in the string color all the way up to the next `"`. Of course it shouldn't be; the `"` here is a literal character.

**Comment by aziz** [comment]
Can not recreate this issue. I've tested in ST2 2221 with its old Ruby.tmLanguage and ST3 3092 with the latest Ruby package from the github repo.

**Comment by FichteFoll** [comment]
Can not either, even though I could at some point (likely when I tagged the issue). Closing as fixed.

**Comment by marnen** [comment]
Great. I'm mostly using Atom now, but I will test Sublime with the latest Ruby package.
