### ISSUE TITLE
Vintage: visual line mode not working with clone views

### ISSUE THREAD

**Issue by blahgeek** [SublimeTextIssues/DefaultPackages#103]
ST 3065, OS X

How to reproduce:

- Open a file
- Open a clone view of the file
- Enter "Visual line mode" by enter "V" and move around

This issue is related to https://github.com/SublimeTextIssues/Core/issues/289

`on_selection_modified` is called more than once, which causes the plugin to leave visual mode.

**Comment by FichteFoll** [comment]
There is actually a github repo for Vintage, so we would prefer if you could report it there: https://github.com/sublimehq/vintage
