### ISSUE TITLE
Read `show_panel_on_build` from view settings

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#105]
_From @ctf0 on February 16, 2015 10:0_

am trying to set `"show_panel_on_build": true` as a default 
and `"show_panel_on_build": false` only for JS, but it seems that this setting is global and it cant have different settings ,so could the current behavior be altered in anyway ?

_Copied from original issue: SublimeTextIssues/Core#679_

**Comment by FichteFoll** [comment]
For some apparent reason this is correct, refer to line 187 of `exec.py`:
```py
show_panel_on_build = sublime.load_settings("Preferences.sublime-settings").get("show_panel_on_build", True)
```

The `build_env` setting however is later read from the view.

I suggest to instead load `show_panel_on_build` setting from the view settings with `self.window.active_view().settings()` to make the above scenario possible.

@ctf0: FWIW, you can patch `exec.py` manually on your machine.

**Comment by ctf0** [comment]
thanx for the heasup but how do i add the `self.window.active_view().settings()` line ,am sorry but i have no knowledge about python.

**Comment by FichteFoll** [comment]
1. Get PackageResourceViewer
2. open `Default/exec.py` with it
3. go to line 187 and replace it with 
```py
show_panel_on_build = self.window.active_view().settings().get("show_panel_on_build", True)
```
4. Save

**Comment by ctf0** [comment]
nice ,this does the trick ,thanx

**Comment by FichteFoll** [comment]
This issue was moved back to the other repo.
