### ISSUE TITLE
SQL syntax highlighter doesn't recognize a string literal containing a trailing backslash as having a closing quote 

### ISSUE THREAD

**Issue by sstillwell** [SublimeTextIssues/DefaultPackages#106]
As an example, copy the script at 

http://www.mssqltips.com/sqlservertip/1584/auto-generate-sql-server-restore-script-from-backup-files-in-a-directory/

and paste it into a new document.  Save as <somefilename>.sql, or choose View > Syntax > SQL.

Line 19 is

SET @backupPath = 'D:\SQLBackups\'

Which is valid SQL since backslashes don't need to be escaped - at least in Microsoft T-SQL.  The problem is that virtually every line after that appears to be part of a giant multi-line literal except where there's another string literal which gets inverted in sense.

**Comment by FichteFoll** [comment]
I don't use SQL, but some googling has told me that the general escape for single quotes in SQL strings seems to be `''`, no backslashes involved. The only situation where backslashes seem to work as escapes is for [newlines](https://technet.microsoft.com/en-us/library/dd207007%28v=sql.110%29.aspx) and for the backslash that would result in such an escape (to make a literal backslash followed by a newline).

In that case the SQL syntax definition is just plain wrong.

If there are however some other SQL syntaxes that I know nothing about, please comment here.

**Comment by FichteFoll** [comment]
I'd also like to add that `'''yeah'` get's matched as two separate strings and that the closing quotation mark does not have the `punctiation` scope associated.

Pretty sloppy I'd say.

**Comment by keith-hall** [comment]
https://github.com/sublimehq/Packages/issues/630
