### ISSUE TITLE
c# syntax highlighting broken by method calls on class level containing a string parameter with multiple words

### ISSUE THREAD

**Issue by g-bon** [SublimeTextIssues/DefaultPackages#108]
C# syntax highlighting breaks when a source file contains a method call where a parameter is a string (not a variable containing a string) composed by multiple words. E.g.: `foo("some thing")` 

OS: Windows 8.1 - 64 bit
Sublime Text 3 build 3065

Example to reproduce the issue:

```C#
public class foo
{
    // All good
    writeSomething("something");

    // This breaks highlighting
    writeSomething("some thing");

    // Broken from here
}
```

![c -hl-broken](https://cloud.githubusercontent.com/assets/1524112/6454917/b8f1d6da-c188-11e4-97f3-8992e8431b53.jpg)

**Comment by nrichards** [comment]
Should be, "method calls at class scope".
![fart cs](https://cloud.githubusercontent.com/assets/704698/10235809/99f1b520-6854-11e5-889f-c2ad3db56b3d.png)

NOTE is also broken here on GitHub:

```csharp
public class Coo
{
    public Object text = ObjectMaker.MakeSomeText ("In order to publish your text, you need to do some texty things 'Like this' and then say hello.");
    public Vector curves;
    int Zoo()
    {
        // All the code after the first double-quote, before <In order to> is incorrectly colored with the QUOTE color, for csharp.
        // Sublime Text v3, Build 3083
    }
}
```

Looks like they're the same library.

**Comment by wbond** [comment]
This issue has been fixed with the latest syntax at https://github.com/sublimehq/Packages. It should be distributed as part of dev build 3112.
