### ISSUE TITLE
Cobalt theme: quote marks change in comments

### ISSUE THREAD

**Issue by allanberry** [SublimeTextIssues/DefaultPackages#109]
Cobalt theme bug:  when lines are commented out, the quote marks in those lines change: double quotes become single; single quotes disappear altogether (change to spaces).

This doesn't affect the source code itself; the quotes are still logically the same, but their appearance changes.  Copying and pasting into a different application, or changing the theme, shows this to be the case.

Cobalt theme:
![screen shot 2015-03-05 at 11 22 10 am](https://cloud.githubusercontent.com/assets/735153/6510836/36e9940a-c32e-11e4-811d-f18726e3d32f.png)

Same window using Monokai theme:
![screen shot 2015-03-05 at 11 22 36 am](https://cloud.githubusercontent.com/assets/735153/6510848/484a95c8-c32e-11e4-9cb8-dc4bf9a9cd99.png)

Macintosh 10.9.5
Sublime Text build 3065

I asked this on [this StackOverflow question](http://stackoverflow.com/questions/28884050), to find a temporary solution.

Thanks

**Comment by FichteFoll** [comment]
Try the Twilight scheme. I suspect this is an issue with the italics variant of your font. Which is it btw?

**Comment by allanberry** [comment]
@FichteFoll Font is Monaco (without antialiasing), which seems to be the edge case.  Here is the relevant stuff from my prefs:

    {
        "font_face": "Monaco",
        "font_options":
        [
            "no_antialias"
        ],
    }

no AA, no font specified:
![screenshot 2015-03-07 11 42 52](https://cloud.githubusercontent.com/assets/735153/6542491/ac2012fc-c4bf-11e4-9662-7cdc280bba98.png)

**no AA, Monaco:**
![screenshot 2015-03-07 11 42 00](https://cloud.githubusercontent.com/assets/735153/6542495/bd33a64e-c4bf-11e4-8b39-57d251a41e2b.png)

AA, no font specified:
![screenshot 2015-03-07 11 50 54](https://cloud.githubusercontent.com/assets/735153/6542526/3b77e236-c4c0-11e4-9dbd-08496209460d.png)

AA, Monaco:
![screenshot 2015-03-07 11 44 44](https://cloud.githubusercontent.com/assets/735153/6542489/9637d358-c4bf-11e4-9050-b7b0d3b6161d.png)

Twilight theme is OK, but doesn't affect issue.

**Comment by FichteFoll** [comment]
Thanks for the shots. What do you mean the Twilight theme "doesn't affect [the] issue"? Does rendering happen correctly or incorrectly?

**Comment by FichteFoll** [comment]
This issue was moved to SublimeTextIssues/Core#713
