### ISSUE TITLE
List more symbols than expected when using "goto symbol" for C language in ST3

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#11]
_From @nash900 on September 30, 2014 3:37_

When using "goto symbol (ctrl+R) " for C language, it lists more symbols than expected. Here is an example file:

    struct dac_module {
    	void *hw;
    };

    void dac_func1(struct dac_module *dev_inst, uint32_t param1)
    {
    }

    void dac_func2(struct dac_module *dev_inst, uint32_t param2)
    {
    }

If using "goto symbol", it will list:

    dac_module
    dac_func1
    dac_module    // should remove, "struct dac_module *dev_inst" is just a pararmeter here
    dac_func2
    dac_module    // should remove

Does it possible to make "ctrl+R" to show symbols but not include those in "()"? Thanks.

_Copied from original issue: SublimeTextBugs/Issues#505_

**Comment by wbond** [comment]
This is fixed in dev build 3110.
