### ISSUE TITLE
C Syntax highlighter breaks on some #define statements

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#112]
_From @statik213 on March 17, 2015 18:59_

I'm running build 3075 on Ubuntu 14.04 64 bit. 

I have seen syntax highlighter bugs with the C syntax before related to #define statements. 

Here's an example of some valid C code that breaks the highlighter. Code after line 268 is not formatted correctly.
 - https://github.com/torvalds/linux/blob/master/drivers/ptp/ptp_chardev.c#L268
 - What it looks like:  
![screenshot from 2015-03-17 14 50 50](https://cloud.githubusercontent.com/assets/81034/6695104/0fd3bba8-ccb5-11e4-95b2-ce2d3f0d3090.png)

The offending line is 
```
#define EXTTS_BUFSIZE (PTP_BUF_TIMESTAMPS * sizeof(struct ptp_extts_event))
```

The following variations seem to make the highlighter happy:
 1.  No parens around sizeof expression
 ```
#define EXTTS_BUFSIZE PTP_BUF_TIMESTAMPS * sizeof(struct ptp_extts_event)
 ```
 ![screenshot from 2015-03-17 14 50 50](https://cloud.githubusercontent.com/assets/81034/6695166/728711a0-ccb5-11e4-9c81-82375b7c7803.png)
 2. Split the definition over 2 lines
 ```
#define EXTTS_BUFSIZE \
	(PTP_BUF_TIMESTAMPS * sizeof(struct ptp_extts_event))
 ```
 ![screenshot from 2015-03-17 14 56 09](https://cloud.githubusercontent.com/assets/81034/6695205/c5f4ee02-ccb5-11e4-913c-870a25fd03d3.png)

I see this bug pretty regularly 

_Copied from original issue: SublimeTextIssues/Core#732_

**Comment by FichteFoll** [comment]
Similar: #36, #68.

**Comment by wbond** [comment]
This is fixed in dev build 3110.
