### ISSUE TITLE
YAML should translate tabs to spaces by default.

### ISSUE THREAD

**Issue by Redoubts** [SublimeTextIssues/DefaultPackages#115]
[Tabs are illegal indentation for YAML files](http://www.yaml.org/spec/1.2/spec.html#id2777534). The editor's default YAML setting should be translating tabs to spaces.

**Comment by FichteFoll** [comment]
The YAML package is in dire need of a rework anyway :/

**Comment by FichteFoll** [comment]
Added via https://github.com/sublimehq/Packages/pull/9.

**Comment by FichteFoll** [comment]
This was fixed via sublimehq/Packages#90.
