### ISSUE TITLE
Incorrect JavaScript syntax highlighting with prototype and IIFE

### ISSUE THREAD

**Issue by dnicolson** [SublimeTextIssues/DefaultPackages#116]
Only the `function(` part is highlighted in the top example:

![screen-shot-2015-04-10-at-08 55 18](https://cloud.githubusercontent.com/assets/2276355/7083278/d7ea0f5e-df5f-11e4-80a1-9e944ab7bf2d.jpg)

Sublime Text Build 3084.

**Comment by FichteFoll** [comment]
I can imagine what went wrong there but thinking about it makes me shudder.

**Comment by FichteFoll** [comment]
Fixed in 3104 dev build, probabably around 3087 though.
