### ISSUE TITLE
Sidebar Theme on OSX

### ISSUE THREAD

**Issue by mika76** [SublimeTextIssues/DefaultPackages#117]
The sidebar never seems to change theme on OS-X.

**Comment by FichteFoll** [comment]
Please describe your procedure.

**Comment by mika76** [comment]
I use color sublime to change themes, but even if I install any theme through the package manager, none of them change the look of the sidebar - it always stays the same style\color of yosemite.

**Comment by FichteFoll** [comment]
You have to restart Sublime Text when changing themes to make them load properly.

**Comment by mika76** [comment]
I just tried it with a bunch of different themes and none of them changes the sidebar. Am I just missing them or is this feature not supported? I'm surprised I can't find a theme that does it.

**Comment by FichteFoll** [comment]
Ah, I understand now. [Color Sublime](https://packagecontrol.io/packages/Colorsublime) uses the notion of "theme" for what is actually a "color scheme" in Sublime Text.


Install one of these to get a "real" theme: https://packagecontrol.io/browse/labels/theme

**Comment by mika76** [comment]
Ah brilliant - thanks for the help :smile:
