### ISSUE TITLE
autocomplete box doesn't suggest previously used attributes (HTML Syntax)

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#118]
_From @bzx on April 15, 2015 11:21_

Whenever I use attributes like "data-*" or "placeholder" in HTML documents, they don't get remembered so when I want to use them again in the same document, the suggestion box doesn't display them. It used to work fine in ST2, now in ST3 it's just not there.

I am not sure if there's a special setting for autocomplete, but I couldn't find it... so if I'm missing some special setting, please let me know what it is.

ST2 screenshot
![st2](https://cloud.githubusercontent.com/assets/654500/7157685/274d0734-e372-11e4-9888-5f19ff89aeeb.png)

ST3 screenshot
![st3](https://cloud.githubusercontent.com/assets/654500/7157688/29a4521c-e372-11e4-8f8a-6992df5eeaed.png)

_Copied from original issue: SublimeTextIssues/Core#799_

**Comment by FichteFoll** [comment]
They are actively exlcuded from the completions via `Packages/HTML/html_completions.py`, which provides the context-aware HTML completions in the first place.

You can fix this locally by installing [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer), running the "Open Resource" command, browsing `HTML/html_completions.py` and then replacing line 137 with
```py
return (completion_list, sublime.INHIBIT_EXPLICIT_COMPLETIONS)
```
(that is, no `sublime.INHIBIT_WORD_COMPLETIONS`).

**Comment by bzx** [comment]
Thank you!

**Comment by FichteFoll** [comment]
Update: for the same reason that words in the buffer are not displaced, completions or snippets are not either.

**Comment by FichteFoll** [comment]
Closing this in order to clean up this repository. If you encounter this and the issue still exists in the latest ST build, please open a new issue at https://github.com/sublimehq/Packages.
