### ISSUE TITLE
Goto Symbol problem with pascal syntax

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#12]
_From @marcosrocha85 on September 24, 2014 12:35_

I noticed a litte bug on newest version of SublimeText 3, when searching for symbols in a pascal file the "Goto Symbol" doesn't match methods wich have a comment before it:

```
TFoo = class
    //This will match
    procedure DoAnyThing;
end;

 //This comment doesn't appear at "Goto Symbol"
procedure TFoo.DoAnything;
begin
    DoBar;
end;
```

![gotosymbolworking](https://cloud.githubusercontent.com/assets/7257227/4388204/35af0dec-43e8-11e4-8641-ef733f60e2e6.png)
![gotosymbolproblem](https://cloud.githubusercontent.com/assets/7257227/4388207/3e24bf8a-43e8-11e4-82e7-a52ba958cba1.png)

_Copied from original issue: SublimeTextBugs/Issues#492_

**Comment by 101100** [comment]
This problem also blocks the syntax highlighting on any line following a comment.  Another solution to this problem would be to use the more complete language definition from the [Pascal Snippets](https://github.com/fnkr/ST-Pascal/blob/master/Pascal.tmLanguage).

**Comment by marcosrocha85** [comment]
Great, actually I used to change Pascal Tm Language file whenever Sublime updates itself. In fact I had to do that on the last release. If that correction could be introduced on next release I would be very grateful.

**Comment by keith-hall** [comment]
This was fixed by https://github.com/sublimehq/Packages/commit/0914caa2c88b7047cc2331b3cdbe65089293be9e
