### ISSUE TITLE
Goto Definition does not reuse tabs in other groups

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#121]
_From @jimlawton on April 20, 2015 13:10_

I use a 2-group setup, generally with library code in the right-hand group. Previously, "Goto Definition" would jump to the implementation in the other group if I already had a tab for the module there, or otherwise open a new tab in the current group. 

Now, however, (and for the last month or more), "Goto Definition" always opens the destination in a new tab in the current group. 

Steps to reproduce:
 1. Set up a 2-group (pane) session in ST.
 2. Open a file with the function definition in one of the groups (Group 1).
 3. Open a file with code calling the function in the other group (Group 2).
 4. In the latter file, right-click on the function name, and "Goto Definition".

Expected result: the cursor jumps to the function definition in Group 1.
Actual result: the cursor jumps to the function definition in a new tab in Group 2.

Details:
 - Build: 3084 
 - Channel: dev
 - OS: Linux (Ubuntu 14.04, x64) 

_Copied from original issue: SublimeTextIssues/Core#813_

**Comment by FichteFoll** [comment]
This issue is a bit tricky. I also noticed this, but I thought about whether I would normally want to open the definition in an open view or in its own view. Usually it would be the 'own view'.

However, currently ST does neither because it will focus and scroll existing views *iff they are in the same group as the quick panel*.

Imo it could be done that shift+enter would always open the definition in a new view while normal enter would focus and scroll the existing view, regardless of group position.
It would look weird with the preview however. That could be either in the same group as the panel, which is direct feedback to the user but has the weird jumping in case you use "enter", or it could be focusing the views in a different group if they exist, which will then jump around during preview.

**Comment by jimlawton** [comment]
Which package controls this behaviour?

**Comment by FichteFoll** [comment]
The Default package. Refer to `Default/symbol.py`.

**Comment by nathikazad** [comment]
Would really appreciate this feature. For instance referencing the same file multiple times opens too many tabs.

**Comment by SCdF** [comment]
I know we're not big fans of "me too" style comments, but I would appreciate a feature that disabled the current way this works and reuses open editors already. My standard workflow is 1/3rd terminal, 2/3 ST3 with two panes, prod code in the first and test code in the second. It's frustrating to goto defintion in a test and have it not jump to the already open code editor in the prod code pane.

**Comment by FichteFoll** [comment]
This issue has been moved back to the other repo.
