### ISSUE TITLE
Bad syntax for lines with more than 16384 characters.

### ISSUE THREAD

**Issue by Juanjo-BBVA** [SublimeTextIssues/DefaultPackages#123]
Hello,

While implementing my own syntax highlighting, I found out that for lines with more than 16384 characters, syntax highlighting doesn't work.

Is this a bug and can be fixed?

Thanks!

**Comment by auscompgeek** [comment]
SublimeTextIssues/Core#513

**Comment by FichteFoll** [comment]
I admire your reading skills in that language highlighting bugs should usually go to this repository (which many people don't seem to have), but unfortunately this is a real core issue - and exists already as a ticket.
