### ISSUE TITLE
Within a <script> tag, anytime I write `</` then `</script>` is autocompleted.

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#124]
_From @silverbucket on April 23, 2015 10:44_

When editing HTML, and within a `<script>` tag, it seems no matter what's going on inside, anytime I enter `</` SublimeText will autocomplete to `</script>`. This is very annoying, especially when editing templates within the HTML file.

_Copied from original issue: SublimeTextIssues/Core#820_

**Comment by wbond** [comment]
Can you give an example of this?

In JavaScript, `</` will never be present except inside of a string. Perhaps you are writing JSX?

If you change the `type=""` attribute of `<script>` to something like `text/x-template`, and write balanced tags, the closing behavior seems to work properly.
