### ISSUE TITLE
Many issues with bash / shell script highlighting

### ISSUE THREAD

**Issue by okdana** [SublimeTextIssues/DefaultPackages#125]
I'm not sure if it would be better to break these up into separate issues, but i wanted to err on the side of not spamming. Sorry if this is too general.

The _Shell Script (Bash)_ highlighter is super super limited and in many cases broken entirely. In particular:

Braces in parameter expansion/interpolation are handled naïvely; any closing brace following the first opening brace (regardless of context) can prematurely close the expanded parameter, potentially breaking the rest of the file.

![screen shot 2015-04-30 at 02 23 22](https://cloud.githubusercontent.com/assets/122095/7408177/f1dc7e44-eedf-11e4-81c6-324ad9a430cf.png)
![screen shot 2015-04-30 at 02 19 36](https://cloud.githubusercontent.com/assets/122095/7408140/5e5e55c0-eedf-11e4-8556-5ddd55d6ad05.png)

Similarly, parameter-expansion operators are handled naïvely — basically if any character used as an operator appears anywhere on the line after the variable name, regardless of context, it's highlighted as an operator. This includes operators that can only appear at the beginning of the expansion, like `!`.

![screen shot 2015-04-30 at 02 31 40](https://cloud.githubusercontent.com/assets/122095/7408324/4852694a-eee1-11e4-80c2-726aed327d3b.png)
![screen shot 2015-04-30 at 02 36 37](https://cloud.githubusercontent.com/assets/122095/7408365/c338f52a-eee1-11e4-9350-629a9a96522f.png)

The 'body' of a parameter expansion (the part after the operator) doesn't 'include' (in the sense of the `tmLanguage` file) other scopes.

![screen shot 2015-04-30 at 03 17 41](https://cloud.githubusercontent.com/assets/122095/7408922/7d8b7880-eee7-11e4-9dd3-7e330121318f.png)

`^` and `,` (upper-case and lower-case, respectively) aren't recognised as parameter expansion operators.

![screen shot 2015-04-30 at 02 28 36](https://cloud.githubusercontent.com/assets/122095/7408258/a03c6e04-eee0-11e4-8da7-5516e6efb782.png)

Variable declarations (arguments to `export`, `declare`, `typeset`, `local`, `readonly`) and un-declarations (`unset`) are not highlighted.

![screen shot 2015-04-30 at 02 43 46](https://cloud.githubusercontent.com/assets/122095/7408490/c132e384-eee2-11e4-948d-dec64919849e.png)

Variable assignments are not highlighted (interpolated variables and variables like `for i in ...` are).

![screen shot 2015-04-30 at 02 41 22](https://cloud.githubusercontent.com/assets/122095/7408448/68b081e4-eee2-11e4-8914-fbdc7afa0d75.png)

Arithmetic constructs are highlighted as a literal strings, except when they appear in double-quotes (or in a `for` loop). Edit: Looks like the theme probably just needs rules to make it not like this. I sort of question the scoping of these constructs as 'strings' though, especially the `(( ... ))` one.

![screen shot 2015-04-30 at 03 03 26](https://cloud.githubusercontent.com/assets/122095/7408739/82d5d814-eee5-11e4-9714-9ed6a5390d73.png)

Command-substitution constructs are highlighted inconsistently. Dollar substitution (`$( ... )`) is highlighted correctly, but the body of a back-tick substitution is highlighted as a literal string. Edit: This may be a function of the theme i was using, sorry. See also edit above.

![screen shot 2015-04-30 at 03 05 47](https://cloud.githubusercontent.com/assets/122095/7408767/d3bbe796-eee5-11e4-89fd-1ecd681216bd.png)

Process-substitution constructs are not highlighted correctly (similar to back-ticks). Edit: Probably theme-related, see also edits above.

![screen shot 2015-04-30 at 03 23 58](https://cloud.githubusercontent.com/assets/122095/7409019/6188a01c-eee8-11e4-8379-79d24de6bfad.png)

Nested interpolations aren't highlighted correctly.

![screen shot 2015-04-30 at 03 40 37](https://cloud.githubusercontent.com/assets/122095/7409293/bbaa8b9e-eeea-11e4-9e24-683b2f8acbbc.png)

The `<<-` operator (heredoc ignoring leading tabs) is not highlighted correctly.

![screen shot 2015-04-30 at 03 21 42](https://cloud.githubusercontent.com/assets/122095/7408993/233f6bd8-eee8-11e4-8597-72fd26cf79fe.png)

Heredoc bodies aren't highlighted as strings (as they are for other languages).

Related to the above, the highlighting doesn't understand the effect of single quotes on a heredoc delimiter.

![screen shot 2015-04-30 at 03 35 45](https://cloud.githubusercontent.com/assets/122095/7409211/0423850c-eeea-11e4-9f03-25e9f39abb55.png)

Literal patterns following a regular-expression operator are not highlighted correctly (should be string or dedicated regular-expression scope).

![screen shot 2015-04-30 at 03 27 40](https://cloud.githubusercontent.com/assets/122095/7409071/e5bda7f6-eee8-11e4-9ff2-52b163c7d1b7.png)

Operators in single brackets aren't highlighted correctly.

![screen shot 2015-04-30 at 03 38 46](https://cloud.githubusercontent.com/assets/122095/7409252/6f1f0a16-eeea-11e4-9e64-17d52e4a783b.png)

The `in` control key word (in `case ... in`) isn't highlighted correctly.

![screen shot 2015-04-30 at 02 45 18](https://cloud.githubusercontent.com/assets/122095/7408508/f5a084d2-eee2-11e4-8299-bce284f1631e.png)

The `break` control key word isn't highlighted correctly.

![screen shot 2015-04-30 at 03 44 32](https://cloud.githubusercontent.com/assets/122095/7409350/4bdf2e0e-eeeb-11e4-8390-2dbacaf9e13f.png)

Semi-colons aren't recognised as operators in `for`-loop arithmetic constructs.

![screen shot 2015-04-30 at 03 47 09](https://cloud.githubusercontent.com/assets/122095/7409382/9c74007e-eeeb-11e4-8748-fcd8d216f475.png)

The appearance of a control key word in a substitution construct will break the construct and potentially all following text.

![screen shot 2015-04-30 at 03 59 03](https://cloud.githubusercontent.com/assets/122095/7409605/44fe83a8-eeed-11e4-90fe-2ac319bb6597.png)

I suppose shell scripts are not very sexy but it seemed useful to at least document these somewhere. Also, i'm sorry if any of these are theme-specific; i tried to rule those out but i may have got distracted trying to write the examples.

**Comment by FichteFoll** [comment]
Thanks for the very detailed report. I suspect the bash syntax will be rewritten anyway shortly, following http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17892, so this will surely be of use.

**Comment by okdana** [comment]
Oh, yeah, i did hear something about that. Thanks for responding!

**Comment by leesei** [comment]
@okdana can you post the file you used to validate the syntax?

**Comment by leesei** [comment]
I discovered an issue with heredoc:

```
cat <<EOF
works fine without space
EOF

cat << EOF
with space it is not ok
EOF
```

BTW, when looking the syntax file, I see that many other syntax (like HTML and MARKDOWN) can be highlighted within the content of heredoc. How to trigger them?

**Comment by okdana** [comment]
I don't have any 'real-world' files i'm comfortable sharing (all stuff from my job), but here's a test file i put together quickly:

https://gist.githubusercontent.com/okdana/45d3fd437e2f97f2ac63/raw/a822842edf8acdb7af4d182bbe18545f36d4c7be/bashsyntax.sh

**Comment by leesei** [comment]
Thanks a lot.
I think the file will help improve any Bash syntax highlighter.

Would you also add the Heredoc white space issue I posted to your Gist?
(Gist has no PR :grimacing:)

**Comment by okdana** [comment]
Updated, sorry. That actually explains why i was seeing some of the behaviour i was, i didn't notice before.

I also noticed that the syntax thing does recognise the `<<-` operator (Ctrl+Shift+P reports `string.unquoted.heredoc.no-indent`) when it's not followed by white-space, though it still highlights the `-` incorrectly.

**Comment by jfcherng** [comment]
I am just trying to fix this issue.
PR: https://github.com/sublimehq/Packages/pull/47

**Comment by okdana** [comment]
That looks awesome, thank you! I will definitely try it out as soon as i'm able.

**Comment by donutbrew** [comment]
I don't see it specifically said here, but when specifying a bash heredoc, everything in the file that follows is formatted as heredoc even after the end of the heredoc.

**Comment by keith-hall** [comment]
note this repo has been deprecated in favor of https://github.com/sublimehq/Packages/issues/434

**Comment by FichteFoll** [comment]
The syntax definition has been rewritten via https://github.com/sublimehq/Packages/pull/1057. I imagine that most, if not all, of this has been fixed. I tested a few test cases manually but am too lazy to type out all of them (since they weren't provided as verbatim text).

If you find any remaining issues with the current bash/shell script highlighting, please open a separate issue on https://github.com/sublimehq/Packages (after confirming it doesn't exist already).
