### ISSUE TITLE
cannot use "Goto Definition" via "Goto" menu on method name with punctuation in Ruby

### ISSUE THREAD

**Issue by bachue** [SublimeTextIssues/DefaultPackages#127]
Hi,

Just found an issue that use Menu -> "Goto" -> "Goto Definition" on some ruby methods whose name contains punctuation(e.g. `abc!`, `abc?`), it always says "Unable to find xxxx". But right click on these methods and choose "Goto Definition", it works.

Reproduce:
- create a ruby file, and content will be like this:

``` ruby
def abc!
  'abc'
end

def abc?
  true
end

def abc
  'abc'
end

abc!
abc?
abc
```
- select the method call `abc!`, choose "Goto" -> "Goto Definition" on the menu, it says "Unable to find abc!"
- right click on the method call `abc!`, choose "Goto Definition", it works and the cursor does jump to the definition of `abc!`.
- repeat these steps on `abc?`, it's the same issue.

OS version: Mac OS X 10.10.3
Sublime version: Sublime Text 3, Stable channel, build 8083

**Comment by FichteFoll** [comment]
Works fine for me. 8084 Win7

**Comment by FichteFoll** [comment]
Still works in the latest dev build 3153.
