### ISSUE TITLE
Javascript annotation doesn't work properly.

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#128]
_From @painty on May 4, 2015 4:35_

In a js file `test.js` which has exactly 3 line codes, no more.
```js
/* annotation */
var a='You Cant Annotate Me By Ctrl + /';
/* annotation */
```
I move cursor to line 2 , then press `ctrl`+`/`
what to expact:
```js
/* annotation */
// var a='You Cant Annotate Me By Ctrl + /';
/* annotation */
```
but on ST3 Win Build3083 X64  it turns out to be
```js
 annotation */
var a='You Cant Annotate Me By Ctrl + /';
/* annotation 
```
Seems that a js file cann't be annotated correctly in sitiation below: a js file which has both `/*some annotaion*/` at the start and the end.

_Copied from original issue: SublimeTextIssues/Core#829_

**Comment by FichteFoll** [comment]
What exactly do you do between these two code snippets and what do you expect to happen?

**Comment by FichteFoll** [comment]
_From @painty on May 4, 2015 9:23_

@FichteFoll
Operation and expection added.

**Comment by FichteFoll** [comment]
Okay, so the issue seems to only appear when the caret is at the end of the line in any of these three lines (not just line 2). It works properly if the caret is anywhere else.

Can you confirm?

**Comment by painty** [comment]
@FichteFoll Yes. And I want to add one more position which triggers the bug: the start of line 2.

**Comment by whidy** [comment]
wow seems css annotating does not work well also sometimes...

**Comment by jrappen** [comment]
Cannot reproduce with cursor anywhere on line 2 except the very end with Build 3111 on Win x64.

**Comment by FichteFoll** [comment]
I can still reproduce on 3111 at the end of any of the lines, as in my earlier comment.

**Comment by FichteFoll** [comment]
This issue has been moved back to the other repo.
