### ISSUE TITLE
Wrong highlighting of Tcl with quotes and unmatched braces inside curly braces

### ISSUE THREAD

**Issue by d-led** [SublimeTextIssues/DefaultPackages#131]
## Summary

Tcl quotes and braces rules are somewhat exotic. The syntax highlighter is confusing the syntactic elements in certain constellations, i.e. expects quoted characters, where no quoting of special characters is possible, such as within curly braces `{ " }`.

## Example

```tcl
set ok1 {["]"]}
set ok2 {["][]"]}
set not_ok {["]["]}
puts $ok1            ;# ["]"]
puts $ok2            ;# ["][]"]
puts $not_ok         ;# ["]["]
```

### Wrong highlighting

![sublime_tcl_syntax](https://cloud.githubusercontent.com/assets/1716584/7744277/48a27cd8-ffa2-11e4-9b80-ee10ef321b06.png)

Note the highlighting after `not_ok`. The `puts` lines should be highlighted normally as commands (functions)

## Sublime Version

3Dev, Build 3086

## Analysis

I haven't investigated further, but the confusion is probably easy to make: the contents within top-level single quotes is not subject to escapes.  Thus, 

```tcl
puts {\"]["]}
puts {\"][\"]}
```
prints

```
\"]["]
\"][\"]
```

and is highlighted as follows (wrong starting from the last curly brace on the first line):

![highlighting2](https://cloud.githubusercontent.com/assets/1716584/7744405/35c163c6-ffa3-11e4-980a-35e594b2c5a5.png)

**Comment by wbond** [comment]
This was fixed in build 3096

**Comment by d-led** [comment]
![image](https://cloud.githubusercontent.com/assets/1716584/14761007/f60a1424-0953-11e6-96c5-11a619237310.png)

**Comment by wbond** [comment]
My apologizes, someone added a test for that with the commit, but I missed the fact that they didn't actually fix it. I'll work on getting that corrected now.

**Comment by wbond** [comment]
Should be fixed by https://github.com/sublimehq/Packages/commit/f89329688ca5076ad02ea4c9710f5c21bacf17b5, which will be part of dev build 3112.

**Comment by d-led** [comment]
ok!

**Comment by d-led** [comment]
![image](https://cloud.githubusercontent.com/assets/1716584/15068339/dc3ded5e-1376-11e6-95a1-5411bee88b49.png)
yay, looks good!

**Comment by d-led** [comment]
hm.. curly braces should probably not be highlighted as strings, as "everything is a string"
![image](https://cloud.githubusercontent.com/assets/1716584/15068440/9b22947c-1377-11e6-9464-6aca5a22e8ad.png)

it should be rather:
![image](https://cloud.githubusercontent.com/assets/1716584/15068479/e9d2d118-1377-11e6-9dc0-1a936f3039db.png)

working example: http://ideone.com/7KsnMz

**Comment by FichteFoll** [comment]
@d-led could you open that as a new issue please?

**Comment by d-led** [comment]
ok

**Comment by FichteFoll** [comment]
Thank you.

**Comment by d-led** [comment]
you're welcome and thanks in return
