### ISSUE TITLE
Wrong CSS highlight syntax

### ISSUE THREAD

**Issue by magic890** [SublimeTextIssues/DefaultPackages#132]
Wrong highlight on minified CSS with comments starts with `/* */`.
I think that line `5` should not be highlighted as comment after the `*/`.
If you go on new line after the closing comment sign, the code line will be highlighted correctly.

![Screen shot](https://cloud.githubusercontent.com/assets/1352670/7836636/e99bcfc0-0481-11e5-9654-1f909ebd8e71.png)

[CSS here](http://pastebin.com/6HnWH3D6)

**Comment by FichteFoll** [comment]
Same issue as https://github.com/SublimeTextIssues/Core/issues/513. Line 5 has 17206 characters, which is >16384. Deleting a few at the end of the line makes it work again.
