### ISSUE TITLE
Incorrect Syntax Hightlighting of Ruby when variable has name 'gem'

### ISSUE THREAD

**Issue by alazarchuk** [SublimeTextIssues/DefaultPackages#133]
OS: Ubuntu Linux (x64)
ST Version: Build 3083

The Ruby code:

```ruby
if ver then
  next if File.exists?(File.join(gem_dir, "#{gem}-#{ver}"))
else File.exists?(gem_dir)
  list = Dir.entries(gem_dir)
  next if list.length > 0
end
```

The bug exists only when the local variable has name 'gem' and used inside double quoted string.

![image](https://cloud.githubusercontent.com/assets/2471454/7988273/2d1d14a6-0aeb-11e5-816d-ff4ca70c780d.png)

**Comment by wbond** [comment]
Since the usage of bundler in Ruby is so pervasive, and a `Gemfile` is just ruby code, highlighting of `gem` seems to make sense to me. I don't think we want to remove this.

**Comment by FichteFoll** [comment]
@wbond the highlighting still breaks in an unacceptable way, at least in the screenshot. 

I don't have experience in Ruby, but `gem` does not seem to actually be a keyword despite its scope.
