### ISSUE TITLE
Tcl not highlighting properly

### ISSUE THREAD

**Issue by MattKonja** [SublimeTextIssues/DefaultPackages#134]
When I use the following code, it causes the text to no longer become highlighted for the remainder of the file.

This issue occurs in both Sublime 2 and 3.
Build 3083

![tclnothighlighting](https://cloud.githubusercontent.com/assets/3956780/8061955/3ba54a30-0e9b-11e5-93a7-d187acca2208.PNG)

**Comment by FichteFoll** [comment]
Related: #131

**Comment by jrappen** [comment]
@MattKonja @FichteFoll I believe you can close this issue now.

**Comment by FichteFoll** [comment]
Added the issue to a new milestone. I will close all associated issues once the next release is published.

**Comment by jrappen** [comment]
:+1:
