### ISSUE TITLE
Unable to open Packages/XML/XSL.tmLanguage

### ISSUE THREAD

**Issue by 0pt1m1z3r** [SublimeTextIssues/DefaultPackages#135]
Error after start:
`Error loading syntax file "Packages/XML/XSL.tmLanguage": Unable to open Packages/XML/XSL.tmLanguage`

`Set Syntax: XSL` missing. I can't use emmet plugin for XSL. XSL disappeared after the last update.

Mac OS X 10.10.3.
Sublime Text 3 Build 3092.

**Comment by FichteFoll** [comment]
I confirmed that the XSL.tmLanguage file was removed starting 3089. I suppose that this was done because the XML.tmLanguage file has been removed in favor of XML.sublime-syntax and XSL included the XML.tmLanguage definition.

**Comment by EzheG** [comment]
I rewrite XSL.tmLanguage to XSL.sublime-syntax. And fix #93 
http://pastebin.com/mRS3azhY
http://pastebin.com/9Q7T26CX
Check please. Can you add this to 3dev?

**Comment by FichteFoll** [comment]
I'm not affiliated with Sublime HQ, but maybe the developer will see this soon enough. You might want to post this in the Build 3092 release topic on the forum, but that's unavailable currently.

**Comment by msoutopico** [comment]
How does the end user fix this issue?

**Comment by halpinsj** [comment]
Is there any way currently to get the XSL type working properly in the current build of ST3? I updated recently and can no longer do the xsl editing using emmet that i had been using extensively.

**Comment by FichteFoll** [comment]
You can extract the XSL syntax from an older build and patch it into your packages folder (either as a separate package or in User; or as an override in the XML package).

**Comment by halpinsj** [comment]
Looking around for where I can download older versions of ST3 and can't find anywhere.

I attempted creating an XSL sublime-package by unzipping the XML sublime-package, going in and changing the .sublime-syntax and .sublime-settings files to reflect the new type then re-zipping the files up and naming the zipped file XSL.sublime-package. It shows up in ST3 as an available type now and automatically is applied to my xsl files and treats the syntax highlighting the same as the XML type which is good, but the emmet shortcuts defined for xsl still do not work for me. I'm not sure what emmet is looking for to decide whether the xsl shortcuts are available.

**Comment by FichteFoll** [comment]
https://forum.sublimetext.com/t/how-to-roll-back-to-3083-on-osx/17338

**Comment by crewone** [comment]
Still an issue in the latest builds :(

**Comment by FichteFoll** [comment]
@wbond added the old XSL syntax as a package that can be installed via Package Control. If you are affected by this, just install it like any other package.

**Comment by wbond** [comment]
If you want to use the old XSL syntax, you can installed via Package Control. See https://packagecontrol.io/packages/XSL.
