### ISSUE TITLE
Sublime 3, bash shell script not highlighted properly

### ISSUE THREAD

**Issue by wirSeefahrer** [SublimeTextIssues/DefaultPackages#136]
When writing code like
```bash
cat << EOF
  if this while we are reading for maybe just an hour
EOF
```

the syntax highlighting feature still tries to highlight bash code (for, if, while)
![2015-06-11_074757](https://cloud.githubusercontent.com/assets/4567226/8100606/8ef1fe1c-100e-11e5-842b-3190b2371cac.png)

Is there a way to fix it by myself and provide a patch file?

**Comment by FichteFoll** [comment]
I don't know the exact syntax, but you can patch this by editing `Packages/ShellScript/Bash.tmLanguage`, using PackageResourceViewer.

**Comment by wirSeefahrer** [comment]
I didn't manage to find it, whats the PackageResourceViewer?

**Comment by FichteFoll** [comment]
PackageResourceViewer is a package that allows you to modify packages easily. See http://docs.sublimetext.info/en/latest/extensibility/packages.html#customizing-or-overriding-packages.

For docs on the format, refer to http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html.

**Comment by leesei** [comment]
I also reported in #136, which has this and more test cases.
I viewed the syntax file and was not sure why there are may rules for defining different contents within Heredoc.
>  I see that many other syntax (like HTML and MARKDOWN) can be highlighted within the content of heredoc. How to trigger them?

**Comment by FichteFoll** [comment]
Actually, the missing heredoc highlighting is also mentioned in #125, so I'm closing this as duplicated.
