### ISSUE TITLE
Vintage keybinding inconsistency

### ISSUE THREAD

**Issue by tucsonlabs** [SublimeTextIssues/DefaultPackages#137]
Some of the vintage keybindings don't work correctly from command mode in ST3. For example while in command mode pressing the ```a``` key should put you in insert mode and append text after the cursor. 

However this only happens if you press ```a``` twice.

**Comment by FichteFoll** [comment]
https://github.com/sublimehq/Vintage

For the moment, try out https://github.com/guillermooo/Vintageous
