### ISSUE TITLE
Reopen closed file on right mouse click on tabs

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#138]
_From @dingo-d on June 15, 2015 13:38_

It would be cool to add 'Reopen Closed File' on right click, when you click on an open file (tabs). Right now there are 'Close', 'Close Other Tabs', 'Close Tabs to the Right', 'New File' and 'Open File'.

I think that it would be practical to add reopen a closed file to the list. Sometimes it just happens that I'd close a file accidentally, and then I need to go to File > Open Recent > Reopen Closed File, or use shortcut on keyboard. But if you already have a mouse in hand, a simple right click is much easier then doing a not so small shortcut.

_Copied from original issue: SublimeTextIssues/Core#894_

**Comment by FichteFoll** [comment]
`Packages/User/Tab Context.sublime-menu`:
```json
[
    { "command": "reopen_last_file", "caption": "Reopen Closed File" }
]
```

-

But yes, this could be the default.

**Comment by dingo-d** [comment]
Great! Works like a charm :)

**Comment by FichteFoll** [comment]
This issue has been moved back to the other repo.
