### ISSUE TITLE
Java syntax highlighting broken when calling a method in field initialization

### ISSUE THREAD

**Issue by codeman38** [SublimeTextIssues/DefaultPackages#139]
The following Java snippet breaks Sublime Text's syntax highlighter:

```java
import java.util.regex.Pattern;

public class SyntaxHighlightingTest {
	private static final Pattern failRegex = Pattern.compile("(\\w+)\\}");

	public static void main(String[] args) {
		System.out.println("Watch out for those brackets!");
	}
}
```

Here's how Sublime Text renders that:

![highlightfail](https://cloud.githubusercontent.com/assets/386563/8193923/304392cc-1446-11e5-9c25-19900611460a.png)

**Comment by codeman38** [comment]
Playing around with this further, it looks like this is a more generalized issue with calling methods in field initializers. The grammar is wrongly interpreting what's to the right of the equal sign as a method *declaration*, rather than a call.

**Comment by FichteFoll** [comment]
Closing this as duplicate since https://github.com/SublimeTextIssues/DefaultPackages/issues/172 has more details.

It has been fixed anyway.
