### ISSUE TITLE
Go: Function arguments and return types aren't highlighted correctly

### ISSUE THREAD

**Issue by Ethan-Bierlein** [SublimeTextIssues/DefaultPackages#141]
![bug](https://cloud.githubusercontent.com/assets/11580295/8398585/6ec3a5dc-1dba-11e5-8e27-22a927742b5f.PNG)

**Comment by keith-hall** [comment]
this is now highlighting correctly, probably it was fixed as part of https://github.com/sublimehq/Packages/commit/db847cef8d906d43932d3e34924366155f40cb7f
