### ISSUE TITLE
Javascript syntax highlighting is broken

### ISSUE THREAD

**Issue by redtopia** [SublimeTextIssues/DefaultPackages#142]
I'm using ST3 build 3094 with the ColdFusion package on Windows 7 x64. Not exactly sure when it broke, but it was recently. I installed an update yesterday, but I was not doing any JS work.

I disabled the ColdFusion package, and JS syntax highlighing is still messed up.

Maybe it's just different... variable names are now white when they used to be another color... can't remember what color.

Also, not sure if this is ColdFusion or not, but this breaks all subsequent syntax highlighting. This code is from a .cfm file that is outputting some javascript. The `<cfif></cfif>` block is conditionally outputing javascript and has never corrupted the syntax highlighting before. The `</cfif>` code has a broken color, and the rest of the file is broken too.

		<script>
		$(document).ready(function() {
			mlBox({
				selector: $('##ml-school-badge')
			});
			<cfif schoolCFC.isDemo AND URL.showabout EQ "1">
			mlBox({
				selector: $('##aboutTeaching'),
				open:true
			});
			</cfif>
		});
		</script>

**Comment by FichteFoll** [comment]
Similar issue on the sublimehq repo: https://github.com/sublimehq/Packages/issues/63

**Comment by redtopia** [comment]
Also added the issue here:

https://github.com/SublimeText/ColdFusion/issues/164

**Comment by FichteFoll** [comment]
The reason why highlighting "breaks" is because ColdFusion is injecting XML tags into the javascript part, and that's obviously not valid javascript. The ColdFusion syntax needs to be updated to use the new sublime-syntax schema and utilize pushing scopes with "with_prototype" and properly match these XML tags by itself.
