### ISSUE TITLE
CSS property values not highlighted for for content and empty-cells properties

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#143]
_From @timovn on July 9, 2015 12:36_

Hi,

Some keywords in CSS language are not recognised.
Including:
- for the "content" property:
  - "open-quote"
  - "close-quote"
  - "no-open-quote"
  - "no-close-quote"
- for the empty-cell property:
  - "show"
  - "hide"

They are not present in the "support.constant.property-value.css" list.

If I understand why the new CSS3-draft keywords are not included, the list above is CSS2 standard:

http://www.w3.org/TR/CSS2/generate.html#content
http://www.w3.org/TR/CSS2/tables.html#propdef-empty-cells

Thanks.

_Copied from original issue: SublimeTextIssues/Core#923_

**Comment by FichteFoll** [comment]
_From @megadr01d on July 9, 2015 14:23_

There's a separate [repo](https://github.com/SublimeTextIssues/DefaultPackages) for default packages issues, including incorrect syntax highlighting.

**Comment by FichteFoll** [comment]
Except for empty-cells' "show" and "hide" property, everything gets highlighted properly now. They are also all completed.

**Comment by keith-hall** [comment]
[empty-cells](https://github.com/sublimehq/Packages/blob/3889492cac950cb90b98db53d94ef47a6b0bd5fe/CSS/CSS.sublime-syntax#L672), [show](https://github.com/sublimehq/Packages/blob/3889492cac950cb90b98db53d94ef47a6b0bd5fe/CSS/CSS.sublime-syntax#L524) and [hide](https://github.com/sublimehq/Packages/blob/3889492cac950cb90b98db53d94ef47a6b0bd5fe/CSS/CSS.sublime-syntax#L469) are all now highlighted, so closing this as fixed.
