### ISSUE TITLE
Add copy filename command and menu

### ISSUE THREAD

**Issue by shivapoudel** [SublimeTextIssues/DefaultPackages#144]
Just like copy_path there should exists a command for copy_filename too.

```python
import sublime, sublime_plugin
import os.path

class CopyFilenameCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        if len(self.view.file_name()) > 0:
            sublime.set_clipboard(os.path.basename(self.view.file_name()))
            sublime.status_message("Copied file name")

    def is_enabled(self):
        return self.view.file_name() != None and len(self.view.file_name()) > 0
```

**Comment by shivapoudel** [comment]
@FichteFoll In which version this will be available. Please reference to support till core default sublime package does support this command `copy_filename`:
https://github.com/wbond/package_control_channel/pull/4680

I mean to say if the core support this on upcoming version then we have to support above package only for certain version. I will love to see this on core as the menu will be available after `Copy File name` which rarely happens in above package :tada:

**Comment by FichteFoll** [comment]
I do not control what gets implemented in Sublime Text core (or shipped packages) because I am not affiliated with Sublime HQ. I do all this on a voluntary basis.

**Comment by FichteFoll** [comment]
This issue was moved to SublimeTextIssues/Core#1187
