### ISSUE TITLE
JavaScript highlighting treats any line starting with a forward-slash as RegEx

### ISSUE THREAD

**Issue by darrylring** [SublimeTextIssues/DefaultPackages#145]
Any line that begins with a forward-slash is treated as the start of a RegEx. It doesn't end until the next forward slash is encountered:

![untitled](https://cloud.githubusercontent.com/assets/2666/8864216/5e766e50-3154-11e5-8c17-8bb2176199d8.png)

**Comment by wbond** [comment]
This was fixed in dev build 3107
