### ISSUE TITLE
Perl: Incorrect RegEx syntax highlighting for default delimiters

### ISSUE THREAD

**Issue by cerasmus** [SublimeTextIssues/DefaultPackages#146]
**Overview**: Incorrect RegEx highlighting occurs when using Perl's default RegEx delimiters `~ //`instead of `~ m//` The basic problem happens when trying to match whitespace characters or patterns that are preceded with whitespace characters.

**Steps to reproduce**:
<img width="545" alt="screen shot 2015-07-31 at 12 02 47" src="https://cloud.githubusercontent.com/assets/11601506/9005165/225b94f8-377c-11e5-878d-766a986e1c31.png">

**Possible fixes**: After hacking around a bit a naive approach to solving the problem might look like this.

Edit `Perl.tmLanguage` and change the match for `string.regexp.find.perl` to be something like this: `<string>(?&lt;!\\)((~\s*)+\/)((\S|\s?).*?)(?&lt;!\\)(\\{2})*(\/)</string>`

OS X 10.10.4
Sublime Text 3 Build 3083

**Comment by FichteFoll** [comment]
Please take a look at https://github.com/sublimehq/Packages (which contains up-to-date syntax definitions of the shipped packages) and consider filing a pull request. Note that `.sublime-syntax` files can only be used from build 3092 onwards.

**Comment by cerasmus** [comment]
Will close issue and test .sublime-syntax with 3092 or later.

**Comment by FichteFoll** [comment]
Please only close issues that are solved (or non-issues).

**Comment by jrappen** [comment]
https://github.com/sublimehq/Packages/blob/12bab0d8ab84b3522812899483c6d100e05c5069/Perl/Perl.sublime-syntax#L342

**Comment by jrappen** [comment]
@cerasmus You'll need to add a test to the change, as Will Bond requires those for new changes to the repo.

**Comment by cerasmus** [comment]
Of course, where do I add a test?

**Comment by FichteFoll** [comment]
Cannot reproduce on 4052.
