### ISSUE TITLE
Tab highlighting changes color before return in PHP files

### ISSUE THREAD

**Issue by danieldulaney** [SublimeTextIssues/DefaultPackages#147]
OS: Windows 10
Version: 3083

In PHP files, the bars or bullets that appears to indicate tabs or spaces when text is selected turn pink if they precede a `return` statement.

To reproduce:
* Set highlighting to PHP.
* Enter the code:
```php
<?php
    return
?>
```
* Select all

The spaces in front of the `return` display in pink.

![image](https://cloud.githubusercontent.com/assets/12433940/9020403/dfa2bb80-37d7-11e5-9645-3ebaee548b86.png)

**Comment by FichteFoll** [comment]
Should be an easy fix, via https://github.com/sublimehq/Packages.

**Comment by wbond** [comment]
This is fixed in the latest version of the PHP syntax at https://github.com/sublimehq/Packages. It will be part of dev build 3112.
