### ISSUE TITLE
Parenthesis in string confuses Java syntax highlighter 

### ISSUE THREAD

**Issue by wangweij** [SublimeTextIssues/DefaultPackages#148]
Pasting the code below into Sublime Text 3 and the 2nd method is considered part of a string literal.

    public class A1 {
	    public static void main(String[] args) throws Exception {
	        throw new Exception
	                ("hello (world)");
	    }

	    void x() {
	    	// Nothing
	    }
	}

However, if I put "throw" and "hello" into one line, it looks OK.

This is Sublime Text b3095 on Ubuntu 14.04.2 64 bit.

![screenshot from 2015-08-03 08 52 05](https://cloud.githubusercontent.com/assets/574013/9029042/6028db1c-39be-11e5-8a50-1e1e8b0a828d.png)

**Comment by chuim** [comment]
Just to add an example that seems to trigger the same condition:

    class MyClass {
        String K_STRING = ImaginaryStaticMethod(");");
    
        functionLooksLikeTextAsAllFollowing() {
        }
    }

**Comment by FichteFoll** [comment]
@chuim your particular example is a duplicate of the "just-fixed" #172.

**Comment by chuim** [comment]
@FichteFoll thanks for the heads up!

**Comment by wbond** [comment]
This is fixed in the latest syntax from https://github.com/sublimehq/Packages, and will be part of dev build 3112.

**Comment by chuim** [comment]
Cool. I'll check it out in the release of the next dev build.
