### ISSUE TITLE
Less than operator not parsed correctly in syntax highlighting in multiline java comments

### ISSUE THREAD

**Issue by bh3605** [SublimeTextIssues/DefaultPackages#149]
The less than operator isn't being parsed correctly in 
/**
*/
style of comments. Check out the picture below.
If you have a '<' by itself it becomes yellow and if you have '<' followed by an alphanumeric character, the character that follows it will be highlighted teal and the '<' is highlighted magenta/that pinkish color.

![capture](https://cloud.githubusercontent.com/assets/3073436/9089350/c3a06926-3b62-11e5-80ed-77bbe07424ad.PNG)

**Comment by FichteFoll** [comment]
For some details, it appears that the `<` is matched as the opening of a HTML tag. I don't know how exactly HTML is parsed in javadoc, but even if this is actually expected and the `<` should be escaped as `&lt;`, it should at least terminate on the end of the comment.

**Comment by FichteFoll** [comment]
Can not reproduce in 3104.
