### ISSUE TITLE
Syntax highlighting bug with quotes embedded in Python string

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#15]
_From @jdb6167 on September 18, 2014 22:36_

Admittedly, this is a trivial issue, but I thought I'd report it nonetheless. 

I have the following string in a Python file: 

```
"INSERT INTO db (username, phone_number, first_name, last_name, \
    street_address, city, state, country, zip_code) VALUES ('"+ username +"', \
    '"+phone_number+"','"+first_name+"','" + last_name + "','" + street_address + "',\
    '" + city +"','" + state + "','" + country + "','" + zip_code + "')"
```

The names following VALUES are local variables. This runs fine in the Python terminal, but Sublime highlights the local variables as being part of the string. I'm running Build 3065 on Ubuntu 14.04.

_Copied from original issue: SublimeTextBugs/Issues#486_

**Comment by wbond** [comment]
This was fixed in dev build 3104
