### ISSUE TITLE
JavaScript syntax should support ECMAScript 2015

### ISSUE THREAD

**Issue by darrylring** [SublimeTextIssues/DefaultPackages#150]
With the ECMAScript 2015 (ES6, ES.next, Harmony, whatever else) standard finalized, the default JavaScript package should support ES6.

https://github.com/lukehoban/es6features provides a concise overview of the new features in ES6.

**Comment by FichteFoll** [comment]
On the dev channel, the syntax from [JavaScriptNext](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax) has been incorporated into the default Javascript syntax def. I assume you are on beta?

**Comment by darrylring** [comment]
Oh, great. My bad for not checking the dev branch. Closing.
