### ISSUE TITLE
Line in multiline comment missing leading asterisk given wrong syntax highlighting

### ISSUE THREAD

**Issue by bh3605** [SublimeTextIssues/DefaultPackages#151]
In java you can have a multiline comment and as long as you specify the leading /*\* and closing */ you can write in between them and not need an asterisk at the beginning. This gives some strange pink highlighting which is wrong.

![capture](https://cloud.githubusercontent.com/assets/3073436/9111217/a34341ac-3c12-11e5-9b97-fedcc119bea0.PNG)

**Comment by FichteFoll** [comment]
Related: https://github.com/sublimehq/Packages/issues/68
