### ISSUE TITLE
Line and block comment toggle is broken in gruntfile.js and gulpfile.js document types

### ISSUE THREAD

**Issue by bmcminn** [SublimeTextIssues/DefaultPackages#152]
Windows 7 Professional 64-bit
ST3: 3083 | Fresh install
Languages: Gruntfile JS, Gulpfile JS
Related Package: https://github.com/YabataDesign/afterglow-theme

---

Comment toggle `cmd + /` or `ctrl + /` doesn't work in Gruntfile JS and Gulpfile JS file types.

Related:
- #44 
- https://github.com/YabataDesign/afterglow-theme/issues/72

**Comment by FichteFoll** [comment]
Not an issue with Sublime Text but with how the package you mention defines its syntax, because it's errorneous. https://github.com/YabataDesign/afterglow-theme/issues/95 fixes that.
