### ISSUE TITLE
C++: Incorrect red highlighting when semicolon is missing after class constructor's curly braces

### ISSUE THREAD

**Issue by christarazi** [SublimeTextIssues/DefaultPackages#153]
Here's a screenshot of the issue.
![screenshot from 2015-08-31 18 39 39](https://cloud.githubusercontent.com/assets/3885308/9594432/bbd954e8-500f-11e5-85dc-b9934761f83a.png)

If I press tab inside the curly braces, then the red highlighting goes after the next method's curly braces. It is happy when I put a semicolon there.

I am using the latest stable version of Sublime Text 3.

If there's any info I'm missing, I'll be glad to add them.

**Comment by TheClams** [comment]
Cannot reproduce this one: the fact that the type string is highlighted makes me believe you are using something different than the default package

**Comment by FichteFoll** [comment]
It *might* have been fixed already in recent builds.
@christarazi, can you still reproduce and if yes, how?

**Comment by christarazi** [comment]
It seems it has been fixed. I'm on the stable 3103 build and I can't reproduce the issue.
