### ISSUE TITLE
Syntax highlighting fails in Python, when raw docstrings with special characters are involved

### ISSUE THREAD

**Issue by avinassh** [SublimeTextIssues/DefaultPackages#158]
Whenever a raw docstring has a special character `(` `)`, even if they are escaped properly, syntax highlighting fails. Following is a valid python script:

    def hi(name):
        r""" Say hi!
        (with a \) special characters.
        """
        return 'hi ' + name

    print(hi('avi'))

However sublime shows everything as a comment:

<img width="578" alt="screen shot 2015-11-01 at 9 32 01 pm" src="https://cloud.githubusercontent.com/assets/640792/10869799/171308bc-80e0-11e5-9c0b-feba490603be.png">

Sublime Version: ST3, build 3083.
OS: OS X 10.11.1
To reproduce: Copy the above code snippet in ST and see the highlighting.

**Comment by Pathangi-Jatinshravan** [comment]
+1 I can confirm that this is an issue.

**Comment by philipbordallo** [comment]
This looks to be fixed in dev build 3095.

<img width="571" alt="screen shot 2015-11-02 at 11 12 13 pm" src="https://cloud.githubusercontent.com/assets/9970403/10902799/2e9d8ad4-81b7-11e5-82a4-2971e89ab3e1.png">
