### ISSUE TITLE
Matlab .m File Syntax

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#160]
_From @krisdestruction on November 19, 2015 20:14_

Sublime does not detect .m as matlab code files for syntax highlighting

_Copied from original issue: SublimeTextIssues/Core#1026_

**Comment by krisdestruction** [comment]
Wait why is this closed?

**Comment by FichteFoll** [comment]
It's not.

**Comment by krisdestruction** [comment]
Oh you closed the other one, gotcha

**Comment by wbond** [comment]
`.m` files are also Objective-C files.

Rather than change Matlab to override Objective-C, breaking existing users' workflows, you can do the following:

 1. Open a `.m` file
 2. Use the *View > Syntax > Open all with current extension as ... > MATLAB*
