### ISSUE TITLE
Bad rule for line comment in Pascal language definition

### ISSUE THREAD

**Issue by Hibou57** [SublimeTextIssues/DefaultPackages#161]
This bug report comes with a proposed fix.

Create a new Pascal file (extension *.pas). Insert this:

    // Some line comment
    procedure

`procedure` should be hilighted as a keyword, but it is not, and is displayed as pure text instead. Adding a space just before, enables highliting of this keyword, which suggests the rule for line comments consumes too much. Indeed, in `Pascal.tmLanguage`, for the `comment.line.double-slash.pascal.two`, if the value for the `end` key is changed from `\n` to `$`, there is no more issue. The same for `comment.line.double-dash.pascal.one`, which is to be fixed too.

Using Sublime Text 3 build 3083.

**Comment by FichteFoll** [comment]
Duplicate: #12
