### ISSUE TITLE
(Suggestion on syntax highlighting) Comments to appear in italics

### ISSUE THREAD

**Issue by darkred** [SublimeTextIssues/DefaultPackages#164]
My suggestion on syntax highlighting is comments to appear in italics. 

It's a feature I've noticed in Atom and I like it a lot.
It helps the user focus on the actual code even better, visually ignoring the comments.

**Comment by MattDMo** [comment]
This is completely dependent on the color scheme you use. Some have comments in italics, others don't. There is no setting in Sublime itself to change this.

**Comment by darkred** [comment]
Thanks for the info.

**Comment by darkred** [comment]
Thanks for the info.

For anyone interested, I changed the comments style to italics in the default color scheme (Monokai)
by changing inside `Monokai (SL).tmTheme` _(via PackageResourceViewer)_ 
from 
```
		<dict>
			<key>name</key>
			<string>Comment</string>
			<key>scope</key>
			<string>comment</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#75715E</string>
			</dict>
		</dict>
```
to 
```
		<dict>
			<key>name</key>
			<string>Comment</string>
			<key>scope</key>
			<string>comment</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#75715E</string>
				<key>fontStyle</key>
				<string>italic</string>
			</dict>
		</dict>
```
i.e. inserted
```
				<key>fontStyle</key>
				<string>italic</string>
```
