### ISSUE TITLE
YAML syntax highlighting breaks with double colons in key names

### ISSUE THREAD

**Issue by alexmuller** [SublimeTextIssues/DefaultPackages#167]
I believe this is valid YAML:

```yaml
---

this::is::a::valid::yaml::key: "this is a valid string value"
```

When I parse it in Ruby I get this which is corrrect:

```ruby
{"this::is::a::valid::yaml::key"=>"this is a valid string value"}
```

But the syntax highlighting in Sublime Text 3083 breaks:

![screen shot 2015-12-24 at 10 35 36](https://cloud.githubusercontent.com/assets/121219/11993542/16914660-aa2a-11e5-8613-2b60f38bf1c2.png)

#41 has a lot of discussion about YAML.

**Comment by FichteFoll** [comment]
A proposed fix for this is already available at https://github.com/sublimehq/Packages/issues/90.
