### ISSUE TITLE
python string show red line

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#169]
_From @nicebug on December 28, 2015 11:14_

in python pycparser module, c_lexer.py, string define with """ show red line.this may be a bug
![image](https://cloud.githubusercontent.com/assets/1947907/12017869/018cb50e-ad97-11e5-9da8-dc5390580b2f.png)

_Copied from original issue: SublimeTextIssues/Core#1053_

**Comment by MattDMo** [comment]
This is fixed in Build 3095.

**Comment by FichteFoll** [comment]
Oh good. I kind of suspected it since 3095 uses a `.sublime-syntax` for Python already, but didn't bother to check.

Thanks for the heads up.

**Comment by nicebug** [comment]
thank you. my build is 3083
