### ISSUE TITLE
Setting default value of typehinted argument to array using short array syntax in PHP

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#17]
_From @marcushat on September 5, 2014 18:37_

In ST3 there is an issue with the php syntax definition. When defining the default value of an argument using the short array syntax(`[ ]`) it highlights the array literal as invalid. It doesn't do this when using 
`array()` instead or without typehinting the argument. Ran the code and no errors or warnings and it works as expected. Only tested on current build 3065 of ST3.

Example(code used when I discovered this):

```php
<?php
function foo(array &$foobar= [] ) { //array literal gets highlighted
}

function foo(array &$foobar= array() ) { //this is fine
}

function foo(&$foobar= [] ) { //this is fine too
}
?>
```

_Copied from original issue: SublimeTextBugs/Issues#470_

**Comment by FichteFoll** [comment]
Can not repro in 3104, but I don't know when it was fixed initially.

**Comment by marcushat** [comment]
Working on 3103 too. Must have been recently because I was still having this issue a couple weeks ago. Glad it's resolved now though
