### ISSUE TITLE
Python syntax definition misses hex escapes with lowercase a-f

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#170]
_From @pbx on December 28, 2015 2:44_

ST 3, build 3083, Linux

When viewing Python source with hex escape codes inside strings, those which use lowercase a-f instead of uppercase A-F get missed by the syntax highlighter. Lowercase in these sequences *is* valid Python.

To reproduce, paste this into a window set to Python syntax. You should see that the lines containing lowercase a-f  are not higlighted like the ones with uppercase A-F:
```
"\x99"
"\x9a"
"\x9A"
"\x9b"
"\x9B"
"\x9c"
"\x9C"
"\x9d"
"\x9D"
"\x9e"
"\x9E"
"\x9f"
"\x9F"
"\xa0"
"\xA0"
"\xa1"
"\xA1"
"\xa2"
"\xA2"
"\xa3"
"\xA3"
"\xa4"
"\xA4"
"\xa5"
"\xA5"
"\xa6"
"\xA6"
"\xa7"
"\xA7"
"\xa8"
"\xA8"
"\xa9"
"\xA9"
"\xaa"
"\xAA"
"\xab"
"\xAB"
"\xac"
"\xAC"
"\xad"
"\xAD"
"\xae"
"\xAE"
"\xaf"
"\xAF"
```

_Copied from original issue: SublimeTextIssues/Core#1052_

**Comment by MattDMo** [comment]
In case you're interested, this and many other bugs are fixed in [Python Improved](https://packagecontrol.io/packages/Python%20Improved).

**Comment by wbond** [comment]
This is fixed in the latest version of the Python syntax at https://github.com/sublimehq/Packages and will be part of dev build 3112.
