### ISSUE TITLE
JS syntax highlighting bug when property of prototype points to IIFE

### ISSUE THREAD

**Issue by Daniel-Hug** [SublimeTextIssues/DefaultPackages#171]
### Reproduce
1. Paste this JS into sublime (it is [good JS](http://jshint.com/)):

    ```js
    Person.prototype.age = (function() {
        return 5;
    })();
    ```

2. Notice the poor syntax highlighting of `function(` which it treats like a parameter:

    ![syntax-highlight-bug](https://cloud.githubusercontent.com/assets/1326984/12217823/435d1266-b6c1-11e5-97ae-40c41048107c.png)

3. Removing `.prototype` fixes the issue:

    ![syntax-highlight-non-bug](https://cloud.githubusercontent.com/assets/1326984/12217940/b22b0704-b6c4-11e5-9fb4-b5cb222ed238.png)

### Environment
 - Windows 8.1 64 bit
 - Sublime Text build 3083

**Comment by FichteFoll** [comment]
Fixed in dev (3095).

**Comment by Daniel-Hug** [comment]
I haven't upgraded my sublime to 3095+ yet so this may have been fixed, but I'll just post here that I see similar results for this code (the comment is highlighted orange like the other parameters instead of being gray like other comments):

```js
function splice(start, deleteCount /*[, newNode1, newNode2]*/) {

}
```

**Comment by FichteFoll** [comment]
Works in 3099 (and 3095 too, likely).
