### ISSUE TITLE
Syntax-selection menu in the status bar too long

### ISSUE THREAD

**Issue by eugenesvk** [SublimeTextIssues/DefaultPackages#174]
There is a very useful **language(syntax)-selection menu** at the _bottom right_ corner of ST3 (in the status bar). However, it's too long because ST3 supports so many languages (which is awesome!). Is there a way to put some of the less frequently used languages in e.g. the "**other**" group?
I know some addons already do that for their supported languages (e.g. I have a **Git** menu that has **Git Blame** and **Git Graph** items), but I'm not sure whether it's possible to do it manually somewhere.

I'm using **Sublime Text 3 build 3103** on a **OS X 10.11.3**

**Comment by FichteFoll** [comment]
Good idea, but unfortunately this is the wrong repository for this since it is an issue regarding the ST core functionality.

In the mean time, I suggest using the command palette for switching syntaxes and optionally defining a custom key bindings for it. Here's mine:
```js
  { "keys": ["ctrl+alt+s"], "command": "show_overlay",
    "args": {"overlay": "command_palette", "text": "Set Syntax: "} },
```

**Comment by eugenesvk** [comment]
@FichteFoll thanks for the tip, will indeed use the shortcut in the meanwhile!
Although would still prefer to have a way to cull the menu since it's not such a frequent operation to warrant remembering a new shortcut.
Will move it to the ST core repo.
