### ISSUE TITLE
JavaScript: Syntax highlighting issue in ternary operator

### ISSUE THREAD

**Issue by Tharit** [SublimeTextIssues/DefaultPackages#177]
It seems like the syntax highlighting somehow looses the context of the ternary operator when a binary operator is used in the "if true" part.
The last operand in the binary operator is then highlighted as if it was an object property (because of the following colon).
This can be "fixed" by wrapping the binary operand in parenthesis.

Example:

```javascript
// highlighted correctly
a = test ? a : b;
// highlighted correctly
a = test ? (a + b) : c;
// b is highlighted as if it was a property
a = test ? a + b : c;
```

![screen shot 2016-02-19 at 15 41 21](https://cloud.githubusercontent.com/assets/1258493/13178479/5d1379b0-d71f-11e5-90ae-d67af97f1e79.png)

Expected behaviour: "b" should never be highlighted as if it was a property.

**Comment by FichteFoll** [comment]
cc @wbond

**Comment by wbond** [comment]
This no longer occurs with the latest version at https://github.com/sublimehq/Packages. Please note the version there has not yet been shipped with a version of Sublime Text and will have some bugs until the next dev build of ST is out.

**Comment by wbond** [comment]
This was fixed a while ago and is part of the recent dev builds.
