### ISSUE TITLE
In shell script I cannot goto certain function definitions

### ISSUE THREAD

**Issue by zkutasi** [SublimeTextIssues/DefaultPackages#178]
I have found, that in Sublime-Text 3 Build 3103, I cannot "goto" to certain function definitions, like:

function unlockAmfSu
{
...
}

If I put it like this:

function unlockAmfSu()
{
...
}

Everything is OK.

I have found the problem is in the syntax file of Shell-Scripting, namely the word "function" is caught by context "pipeline". This causes that the indexer is not picking up these functions as definitions, so the "goto" does not work.

I have found two solution: remove "function" from pipeline, OR reorder the includes at the beginning of file Shell-Unix-Generic.sublime-syntax, to include function-definition earlier.

**Comment by FichteFoll** [comment]
@rwols looking at this briefly, the first example *does* end up being scoped as `entity.name.function`, but the trailing newline is also scoped. Maybe you want to take care of this?

![2017-11-08_17-31-34](https://user-images.githubusercontent.com/931051/32560750-bd240750-c4aa-11e7-9ec2-f0e3aae7e02e.png)
