### ISSUE TITLE
ST3 - CSS Comments Initiated With `Ctrl+/` Lack the Standard Whitespace

### ISSUE THREAD

**Issue by lunacodes** [SublimeTextIssues/DefaultPackages#179]
When you press Ctrl+/, the comments come out like `/*Comment Here*/` instead of `/* Comment Here */` as would be the expected standard.

Fix: in the `CSS Module -> Comments.tmPreferences` edit as follows

17: Change `<string>/*</string>` to `<string>/* </string>`
23: Change `<string>*/</string>` to `<string> */</string>`

I'd be happy to submit a Pull Request for this if that's allowed

**Comment by FichteFoll** [comment]
Pull requests should go here: https://github.com/sublimehq/Packages

**Comment by lunacodes** [comment]
Great, Thanks!  

I will submit one later tonight.

**Comment by wbond** [comment]
For historical record: GitHub incorrectly closed this. A PR was accepted that at one point had changed the whitespace, but we reverted the change after discussion.

Either way, it is fine that this is closed, as discussed at https://github.com/sublimehq/Packages/pull/228.
