### ISSUE TITLE
Ruby code folding improper when using implicit begin blocks on method

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#18]
_From @jptalton on September 4, 2014 13:16_

OSX ST3 3065

when using implicit begin blocks on methods, with proper indentation, the folding ends at the rescue leaving the rest of the code 'dangling'

  def foo
    ...
  rescue
    ...
  end  

this will result in a folding that loos like:

  def foo [...]
  rescue
    ...
  end

https://github.com/bbatsov/ruby-style-guide#begin-implicit

_Copied from original issue: SublimeTextBugs/Issues#465_

**Comment by keith-hall** [comment]
https://github.com/SublimeTextIssues/Core/issues/101
