### ISSUE TITLE
YAML syntax highlight error involving quotes and brackets/braces

### ISSUE THREAD

**Issue by sparr** [SublimeTextIssues/DefaultPackages#183]
```
- foo: bar "}"
  wrong-color: baz
```

Everything after `}"` is mis-identified as a continuation of the string.quoted.double.yaml that started at the first `"`. This problem also happens with single quotes, and with a closing bracket instead of a closing brace. Having a matching opening brace/bracket does not affect the problem. Removing the text `bar ` makes the problem go away. The next `"` anywhere in the file will end the string context and return highlighting to normal.

The YAML syntax definition in https://github.com/clifford-github/sublime-ansible does not exhibit this bug.

**Comment by FichteFoll** [comment]
This should have been fixed with 3109. Which build are you using?

**Comment by sparr** [comment]
I was using 3107. This does seem to be fixed in 3109.
