### ISSUE TITLE
Ruby & Python syntax coloring stops after utf8 char in subclass name

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#19]
_From @jptalton on September 3, 2014 16:50_

OSX ST3 3065

when creating a class that subclasses a class with a non-ascii char, the syntax coloring is lost

class Foo < BárBizQux
end

while "B" is colored
"rBizQux" is not colored

_Copied from original issue: SublimeTextBugs/Issues#460_

**Comment by wbond** [comment]
This has been fixed in the Python syntax at https://github.com/sublimehq/Packages. That version will be part of dev build 3112.

The Ruby syntax has not been addressed yet.

**Comment by keith-hall** [comment]
This was fixed by https://github.com/sublimehq/Packages/commit/ce7cd7b06bd28815c9cd471a40d623ec60995ff4
