### ISSUE TITLE
Python: from in `yield from` statement incorrectly highlighted

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#20]
_From @FichteFoll on September 3, 2014 3:58_

Since Python 3.3 the `from` keyword may also be used in the `yield from <expr>` statement and should not be marked as `keyword.control.import.from` in this case.

![2014-09-03_05 55 32](https://cloud.githubusercontent.com/assets/931051/4129348/480982fe-331e-11e4-8b42-0ebcd4b7df58.png)

_Copied from original issue: SublimeTextBugs/Issues#459_

**Comment by wbond** [comment]
This is fixed in the latest version of Python at https://github.com/sublimehq/Packages and will be part of build 3112.
