### ISSUE TITLE
$ in JavaScript is matched as keyword.operator (and generally incorrectly)

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#21]
_From @FichteFoll on August 20, 2014 22:41_

Dollar signs (`$`) are valid characters for any javascript identifier, which probably everyone knows since jQuery.

[From the ECMAScript specification:](http://stackoverflow.com/a/22244840)

>The dollar sign ($) and the underscore (_) are permitted anywhere in an identifier. The dollar sign is intended for use only in mechanically generated code.

Thus, the following code is highlighted wrong:
```js
$test = $(".test");
$function = "this is an identifier, not a keyword";
some$var$ = 1;
```

![2014-08-21_00 23 48](https://cloud.githubusercontent.com/assets/931051/3989418/74951a22-28ba-11e4-827c-4020ad714b0d.png)

In the above snippet, `(?<![a-zA-Z_])\$(?![a-zA-Z_])` matches only the dollar sign in `$(".test")` and should be matched as `variable.other.dollar-sign` or similar.

_Copied from original issue: SublimeTextBugs/Issues#431_

**Comment by FichteFoll** [comment]
Is `source.js variable.other.dollar.js punctuation.dollar.js` now.

See also https://github.com/sublimehq/Packages/issues/141.
