### ISSUE TITLE
Javascript commenting highlighting incorrect

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#22]
_From @nimr0d on August 18, 2014 20:4_

Used $().append("" + 
                           "" +                 
                           ""); 
to include some html script tags. Inside the quotes are some backslashes for escaping quotes. I commented out a few of the lines (i.e. "" + ) and some are highlighted correctly, but some are not highlighted at all. Chrome renders the javascript with the commenting how I intended, so the problem is with sublime.

_Copied from original issue: SublimeTextBugs/Issues#428_

**Comment by FichteFoll** [comment]
No idea what this is about, but it's probably fixed now.
