### ISSUE TITLE
Quote Highlighting Carried To EOF in Objective-C  

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#23]
_From @nrichards on December 3, 2014 3:25_

The quote (") syntax highlighting can carry on highlighting until the end of file, skipping / ignoring an opening quote, honoring only the closing quote, given a specific Objective-C code block.

I expect for the quote character to start highlighting at an opening quote.

OSX
Sublime 3 Build 3065
Clean ST profile

1 Create a new Objective-C file, e.g. "foo.m"
2 Input the following code block:
 ```objectivec
 - (void)foo {
   NSCAssert((1), @";");
   int four = 4;
 }
 ```
3 NOTICE the latter lines, beginning with `int`, are highlighted as if quoted.

Expecting the `int` line to not be quoted. Xcode renders this code correctly.

ASIDE: The markdown engine here on github.com appears to also have the same highlighting bug. 

_Copied from original issue: SublimeTextBugs/Issues#591_

**Comment by wbond** [comment]
This was fixed in dev build 3110
