### ISSUE TITLE
Bash syntax highlighting: keywords match when next to hyphen or slash

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#24]
_From @samhitov on December 2, 2014 19:18_

Keywords like `case` are highlighted red. But they should not be highlighted red when next to a hyphen or slash, as in `sort --ignore-case` or `stat /var/log/case/suitcase.log)`.

In this situation, case should be treated as though it were any other word.

Here are two examples (build 3065):
![image](https://cloud.githubusercontent.com/assets/1392972/5268752/3156b844-7a2a-11e4-85fc-80af19851690.png)

![image](https://cloud.githubusercontent.com/assets/1392972/5269081/74640ecc-7a2d-11e4-849a-cfe3b31042e8.png)

After the keyword match, all code that is normally white is highlighted yellow instead.

_Copied from original issue: SublimeTextBugs/Issues#590_

**Comment by keith-hall** [comment]
this is being tracked at https://github.com/sublimehq/Packages/issues/434

> Consume identifiers including `-` so partial commands/functions aren't highlighted
