### ISSUE TITLE
JavaScript syntax highlighting: Block comment inside function parameter list

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#25]
_From @dalgard on August 17, 2014 16:55_

It's possible to outcomment a parameter in a function declaration/expression like this: `function (/*param,*/ otherparam) {}`. Currently this doesn't get highlighted as a comment. Thanks :)

_Copied from original issue: SublimeTextBugs/Issues#425_

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
