### ISSUE TITLE
JavaScript syntax highlighting: Scientific notation (numbers)

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#26]
_From @dalgard on August 16, 2014 21:13_

It seems the syntax highlighter doesn't recognize numbers written on the form `1e9` (or for instance `1.0001e6`). Thanks in advance.

_Copied from original issue: SublimeTextBugs/Issues#423_

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
