### ISSUE TITLE
C++ syntax highlighting issue with struct in function

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#27]
_From @NiklasRosenstein on August 14, 2014 7:20_

```cpp
static bool FooBar(int argc, char** argv)
{
  struct Args {
    void* hello;
    void* foobar;
    Args()
    : hellp(nullptr),
      foobar(nullptr)
    {
    }
  } args;

  for (int i=0; i < argc; ++i)
  {
  }
  return true;
}
```

Looks like this in Sublime (Build 3059)

![sublime-error](https://cloud.githubusercontent.com/assets/1318438/3916940/3b0a4250-2383-11e4-98d7-0a34e6d4f7f0.png)

Stripping the for-loop or the struct makes it valid again.

_Copied from original issue: SublimeTextBugs/Issues#420_

**Comment by TheClams** [comment]
Fixed in PR https://github.com/sublimehq/Packages/pull/28

**Comment by wbond** [comment]
As of dev build 3110 this is no longer shown as broken. The latest syntax files at https://github.com/sublimehq/Packages, which will be part of build 3112, contain detection of function-local data structures and show them in the Goto Anything panel.
