### ISSUE TITLE
Java enum comments not recognized in ST3

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#28]
_From @winny- on August 14, 2014 0:10_

Comments between constants in an enum declaration are not recognized.

![screen shot 2014-08-13 at 19 08 59](https://cloud.githubusercontent.com/assets/3893828/3914471/3622ca82-2347-11e4-863f-ccb8b424ecc5.png)

Perhaps the Java syntax highlighting borrows from the C++ syntax highlighting, as it appears to have a very similar issue (#361)?

_Copied from original issue: SublimeTextBugs/Issues#419_

**Comment by FichteFoll** [comment]
sample code:

```java
public enum Stuff {
    
    // line comment
    UPLOAD("upload"), /* block comment */
    // another line comment
    DELETE("delete");

    // works again
}
```

**Comment by wbond** [comment]
This is fixed in the latest version of the Java syntax at https://github.com/sublimehq/Packages and will be part of dev build 3112.
