### ISSUE TITLE
Incorrect Syntax Hightlighting of Ruby

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#29]
_From @taroxd on July 26, 2014 3:36_

OS: Windows 7 (x64)
ST Version: Build 3059

The Ruby code:

``` ruby
def something
  index = 10
  index / 2
end

```

The bug exists only when the local variable is named 'index'

_Copied from original issue: SublimeTextBugs/Issues#398_

**Comment by wbond** [comment]
This was fixed at https://github.com/sublimehq/Packages/tree/master/Ruby in 2016.
