### ISSUE TITLE
JavaScript RegEx highlighting is wrong for slashes within sets/ranges

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#3]
_From @MrSimonHagger on November 26, 2014 21:44_

Edited by @FichteFoll (2014-11-26):

Regular expressions in JavaScript may have forward slashes in set/ranges without escaping.

http://stackoverflow.com/questions/9226731/escape-forward-slash-in-jscript-regexp-character-class

```js
var short_regex = /[this is a set/]this should still be part of the regex/;
```

![2014-11-26_22 56 58](https://cloud.githubusercontent.com/assets/931051/5209509/e2af33f6-75bf-11e4-917a-15e3d9380dc2.png)

Workaround: Escape all forward slashes with `\`.

---

Original content:

When the following valid JavaScript RegEx is added into a .js file the code colour hinting stops working beyond the point of inclusion.

It looks like the code hinting is breaking at some point along the RegEx expression.  To see the bug add the following to a JavaScript file and look at the effect on the code colouring afterwards:

```js
var test_regex = /^([A-Za-z0-9!#$%&'*+\-/=?^_`{|}~]+(\.?[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~])*)@([a-zA-Z0-9\-_]+)(\.[a-zA-Z0-9\-_]+)+$/;
```

_Copied from original issue: SublimeTextBugs/Issues#584_

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
