### ISSUE TITLE
Python: incorrect syntax highlighting for SQL expr with comments

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#30]
_From @spumer on July 25, 2014 7:1_

When you use SQL-style comment in SQL expression in single-line string the Sublime Text will comment closing quote too.

How to reproduce:
1. Use Python syntax
2. Type: 'SELECT * FROM "table" --'
![python_string_sql_comment_error](https://cloud.githubusercontent.com/assets/735150/3698807/788d268e-13c9-11e4-9460-4e753384ce62.PNG)

Using software:
Sublime Text 3 (build 3059)
Windows 7 x64 Professional

_Copied from original issue: SublimeTextBugs/Issues#395_

**Comment by FichteFoll** [comment]
Works in 3104.
