### ISSUE TITLE
C++ Syntax - using namespace with attributes

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#31]
_From @blipi on July 18, 2014 13:2_

Using the following syntax:
``using namespace NAME __attribute__((__strong__));``
Makes the editor stop coloring code.

Sublime Text 3 (3059)

_Copied from original issue: SublimeTextBugs/Issues#385_

**Comment by wbond** [comment]
This was fixed in dev build 3110.
