### ISSUE TITLE
C/C++ syntax hightlight does not recognize standard scanf modifier 'm'

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#32]
_From @gatopeich on July 3, 2014 8:26_

This is a correct scanf that looks bad with current C syntax:
```C
scanf("%ms", &buf);
```
This is how it looks in my soda dark theme:
![scanf-bad-syntax](https://cloud.githubusercontent.com/assets/7722268/3467132/b44655e0-028c-11e4-8223-b68a078be360.png)

See http://man7.org/linux/man-pages/man3/scanf.3.html#NOTES

_Copied from original issue: SublimeTextBugs/Issues#365_

**Comment by wbond** [comment]
This is fixed in the latest syntax definitions at https://github.com/sublimehq/Packages and will be part of dev build 3112.
