### ISSUE TITLE
C++ enum class Comments Not Detected

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#34]
_From @tikiking1 on July 2, 2014 3:19_

```c++
enum class enum_type : backing_type // This is a valid comment, but ST3 disagrees.
// Same here.
// It restarts normal behaviour after it finds a '{', even when that's in a comment.
{
    ENUM_MEMBER
};
```

![screenshot from 2014-07-01 22 09 33](https://cloud.githubusercontent.com/assets/4196789/3451446/3db92f7e-0197-11e4-8035-18bce6c8e85c.png)

_Copied from original issue: SublimeTextBugs/Issues#361_

**Comment by wbond** [comment]
This was fixed in dev build 3110.
