### ISSUE TITLE
Certain special words in Rails are not recognized

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#35]
_From @maletor on July 1, 2014 22:41_

Refer to https://github.com/SublimeColors/Solarized/issues/30 for a graphical explanation.

`respond_to` and other Rails 3 symbols are available but it stops short of `before_action` and probably others.

_Copied from original issue: SublimeTextBugs/Issues#360_

**Comment by wbond** [comment]
`before_action` and a few others have been added since dev build 3108. Please open a new issue at https://github.com/sublimehq/Packages/issues if you know of any additional methods that should be included.
