### ISSUE TITLE
Syntax colorer problem after #define

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#36]
_From @SmallRoomLabs on June 20, 2014 6:1_

I've got a .h -file that is colored incorrecty for the statement directly following this particular #define. On ST3 Stable Channel Build 3059.  I'm using the "Blackboard" color scheme, but the problem seems to exist on all schemes.
```
#define PACKED __attribute__((aligned(1),packed))

typedef struct PACKED {
	int foo;
} FOO_t;

typedef struct PACKED {
	int bar;
} BAR_t;
```
As can be seen in the screenshot the first 'typedef struct PACKED' is not colored correctly.

![screen shot 2014-06-20 at 12 56 59](https://cloud.githubusercontent.com/assets/325326/3336924/ef54b66a-f83f-11e3-8ab6-a0f1ec5bb23c.png)

_Copied from original issue: SublimeTextBugs/Issues#348_

**Comment by wbond** [comment]
This was fixed in dev build 3110.
