### ISSUE TITLE
Javascript Snippets have semicolons after blocks and are inconsistent

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#37]
_From @AnnanFay on May 31, 2014 20:25_

The Javascript snippets drive me crazy.

This issue was reported before in a different project but doesn't seem to have gotten over here (https://github.com/jshint/jshint/issues/423)

The snippet code should really follow best practices.

_Copied from original issue: SublimeTextBugs/Issues#307_

**Comment by FichteFoll** [comment]
This has been fixed earlier this year, but I forgot the build number.
