### ISSUE TITLE
Instantiating Scala classes without parameterization causes highlighting bug

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#38]
_From @ddickstein on May 12, 2014 13:29_

I am using ST3 on Mac OS X Mavericks.  Here is my code:

```
class Rational {
  def foo = "bar!"
}
println ((new Rational).foo)
```

The current code for Sublime's Scala package seems to want to stop highlighting the class name when it encounters a space or an open left parenthesis.  This works when the class takes parameters to be instantiated.  However, in this case, there are no parameters to pass, so the class can be instantiated without parentheses.  Sublime highlights from the R in Rational all the way to the end of the line in blue because it has not yet come across a token that would indicate the end of the class name.  I think the fix here would simply be to add close parentheses to the list of tokens that would indicate the end of the class name.

_Copied from original issue: SublimeTextBugs/Issues#285_

**Comment by wbond** [comment]
The Scala syntax was pretty much completed rewritten in 2016 at https://github.com/sublimehq/Packages/tree/master/Scala. This appears to be fixed.
