### ISSUE TITLE
[syntax highlihting][Java] comment after code with bracket are recognized as code

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#4]
_From @leesei on November 18, 2014 17:49_

Paste the following code into Sublime Text 3, set syntax as Java.

```java
class Foo {
    // this comment is ok()
    int bar; // this comment() is recognized as code
}
```

_Copied from original issue: SublimeTextBugs/Issues#572_

**Comment by wbond** [comment]
Currently the Java syntax is in poor shape. There is definitely a rewrite in its future.

For now, this bug has been fixed with the latest version of the syntax available at https://github.com/sublimehq/Packages and it will be part of dev build 3112.
