### ISSUE TITLE
Python syntax highlighting error when `CREATE` keyword present

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#40]
_From @ochawkeye on March 31, 2014 16:4_

Sublime Text 2 Version 2.0.2, Build 2221 (Windows 7) & Sublime Text 3 Build 3059 (Windows 8)

Python string syntax highlighting breaks when the word `CREATE` is used in combination with quotation marks.

```python
print "CREATE '%s'" % ('abc')  # Missing highlighting
print 'CREATE "%s"' % ('def')  # Missing highlighting
print "GRANT '%s'" % ('ghi')  # Highlighting ok
print "CREAT '%s'" % ('jkl')  # Highlighting ok
print "CREATE %s" % ('mno')  # Highlighting ok
print "create '%s'" % ('pqr')  # Highlighting ok
```
![sublime text syntax highlighting](https://cloud.githubusercontent.com/assets/2996205/2569536/e431eb04-b8ed-11e3-8594-4d3af1e94f16.png)

Expected behavior would be for `%s` to display in purple in all cases.

_Copied from original issue: SublimeTextBugs/Issues#269_

**Comment by MattDMo** [comment]
Release 1.4.2 of PythonImproved addresses this (in a rather heavy-handed way) by completely removing SQL highlighting from strings. Not everyone works with SQL, and it was distracting at best and completely wrong at worst (see above), so I got rid of it. Comments are welcome on the PythonImproved issues page if you'd like to discuss this further.

**Comment by FichteFoll** [comment]
Works in 3104, probably earlier already.
