### ISSUE TITLE
Incorrect syntax highlighting for yaml with quoted colon

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#41]
_From @remmelt on March 21, 2014 10:24_

Reproduce by pasting the following yml into a new file:

```
---
- name: Add Logstash repository
  apt_repository: 
    state=present
    repo="deb http://packages.elasticsearch.org/logstash/1.3/debian stable main"
    update_cache=yes
  sudo: yes

```

Actual behaviour: incorrect syntax highlighting, which looks like this:

![screen shot 2014-03-21 at 11 15 02](https://f.cloud.github.com/assets/1133496/2481859/f6a0ebc8-b0e1-11e3-9bce-e1922c8344e4.png)

Expected behaviour: correct syntax highlighting. I assume that would look like this, note the missing colon:

![screen shot 2014-03-21 at 11 19 27](https://f.cloud.github.com/assets/1133496/2481871/55443ca2-b0e2-11e3-8a75-3ec6f8a03ef0.png)

_Copied from original issue: SublimeTextBugs/Issues#266_

**Comment by redbar0n** [comment]
This is actually due to ST correctly following the YAML specs. 

Characters like \ % , etc. are special characters in YAML, and should be inside a string surrounded by quotation marks. Otherwise YAML might think it is supposed to interpret those characters, according to it's spec.

For strings with substrings, use "String with 'substring'." or vice versa (swap the " and ' characters).

**Comment by FichteFoll** [comment]
While you are right for scalars, I don't think this is relevant to block strings nor the bug in this bug report, which is not exactly the issue reported by @remmelt as the real outcome of the yaml text in OP is the following:

```yaml
---
- name: Add Logstash repository
  apt_repository: 
    state=present
    repo="deb http://packages.elasticsearch.org/logstash/1.3/debian stable main"
    update_cache=yes
  sudo: yes
```

```py
>>> yaml.load(view.substr(sublime.Region(0, view.size())))
[{'name': 'Add Logstash repository', 'apt_repository': 'state=present repo="deb http://packages.elasticsearch.org/logstash/1.3/debian stable main" update_cache=yes', 'sudo': True}]
```

Multi-line stuff in the yaml syntax is generally plain broken, just as it doesn't recognize type specifiers like `!str`.

**Comment by muhqu** [comment]
> @redbar0n wrote:
> For strings with substrings, use "String with 'substring'." or vice versa (swap the " and ' characters).

Well, following YAML's spec for [Double-Quoted Strings](http://yaml.org/spec/current.html#\ escaping in double quoted style/) it is absolutely valid to use <kbd>\"</kbd> to escape double-quotes within a double-quoted string...

[Single-Quoted Strings](http://yaml.org/spec/current.html#id2534365) however don't allow backslash-escape-sequences. Therefor a single-quote within a single-quoted string has to be escaped by another single-quote: <kbd>''</kbd>

``` yaml
---
- single_quoted: 'string with ''substring''.'    # string with 'substring'.
  double_quoted: "string with \"substring\"."    # string with "substring".
```
