### ISSUE TITLE
Renew Ruby on Rails snippets

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#42]
_From @tadast on February 15, 2014 12:1_

I've been working on renewing Ruby on Rails snippets for ruby >= 1.9 and Rails >= 3 in [this repo](https://github.com/tadast/sublime-rails-snippets). 

The default snippets are built for ruby 1.8 and Rails 2. Both are no longer supported by the maintainers. Moreover, the syntaxes differ a lot and default snippets that come with ST are nearly useless for projects using current versions of ruby and Rails.

My repo is fairly popular and widely used, however, it is quite problematic to get it working seamlessly, because the default Rails package needs to be manually removed to avoid conflicts. Any chance to merge my fork so that it comes as a default Rails package?

_Copied from original issue: SublimeTextBugs/Issues#247_

**Comment by keith-hall** [comment]
Feel free to submit a PR here: https://github.com/sublimehq/Packages/tree/b03686a46ec3aef97098a636df0348600aca6933/Rails/Snippets

**Comment by FichteFoll** [comment]
Closing as timeout.
