### ISSUE TITLE
Comments do not work in AppleScript Syntax

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#44]
_From @clarkewd on March 20, 2014 4:8_

Comments do not work when the syntax is set to AppleScript ( neither `Toggle Comment` or `Toggle Block Comment` )

It looks like the file `AppleScript.tmLanguage` is a very old release, maybe it should at least be updated to [the changes from the TextMate version](https://github.com/textmate/applescript.tmbundle/commits/master/Syntaxes/AppleScript.tmLanguage) which is now 2 years old but has a commit with the message, `Improve comment.line match.`

The ST3 included applescript syntax even has this note in it (line 155):

	...
	<key>comment</key>
	<string>
		This is not a very well-designed rule.  For now,
		we can leave it like this though, as it sorta works.
	</string>
	...

Also, it looks like the file [Comments.tmPreferences](https://github.com/textmate/applescript.tmbundle/blob/master/Preferences/Comments.tmPreferences) should also be included to get the omments to work

_Copied from original issue: SublimeTextBugs/Issues#265_

**Comment by bammoo** [comment]
How goes it?

**Comment by bammoo** [comment]
I write a plugin for solving this: https://github.com/bammoo/BM-Applescript-Toggle-Comments

**Comment by wbond** [comment]
This is fixed at https://github.com/sublimehq/Packages, and will be part of dev build 3112
