### ISSUE TITLE
Wrong indentation for Javascript/JSON

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#45]
_From @leesei on February 5, 2014 4:57_

OS and OS version: LDME UP7 / Linux Mint 15

Sublime Text Version: 3059

Did you tried to revert to a freshly installed state? no

### Bug Description:
- Wrong indentation for Javascript/JSON

### How to reproduce:
- Open Javascript/JSON file (with proper indentation)
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>: Reindent Lines
- Indentation is wrong

Before
![before](https://f.cloud.github.com/assets/544400/2084429/eba18972-8e21-11e3-83b7-9bd8510dc868.png)

After
![after](https://f.cloud.github.com/assets/544400/2084428/eb9ee65e-8e21-11e3-8836-a42f50d97c48.png)

_Copied from original issue: SublimeTextBugs/Issues#234_

**Comment by wbond** [comment]
https://github.com/sublimehq/Packages now includes indentation rules for JSON. They will be part of dev build 3112.
