### ISSUE TITLE
Ruby syntax highlighting should highlight require_relative like require.

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#46]
_From @envygeeks on January 15, 2014 6:14_

`Kernel#require_relative` was added in 1.9 and behaves like `Kernel#require` 

_Copied from original issue: SublimeTextBugs/Issues#216_

**Comment by aziz** [comment]
This should be closed now. https://github.com/sublimehq/Packages/commit/87ac0cc848c66d25b6c369b7e77d553de042d6c8
