### ISSUE TITLE
C++ Syntax highlighting lost in long files

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#47]
_From @Shirk on January 13, 2014 8:39_

This is a copy of '[Syntax highlighting broken in long C++ Sources] (http://www.sublimetext.com/forum/viewtopic.php?f=3&t=14726&start=0&sid=f35e271a2af4404360dec921be84144d)' as can be read on the forums.

I have a C++ file implementing a state machine which consists of roughly 20+ inline C++ class definitions in about 800 lines of code.

With ST2 I could work with this file just fine and the syntax and scope was detected down to the very last line.
ST3 however stops highlighting (and as it looks to me) scope detection somewhere after about half of my code.

I can reproduce this even with a sample file containing a dummy of what my code looks like but using only empty states.
Each class resembles something like this:

```C++
class SubStateXX : public BaseState //{{{
{
public:
   SubStateXX( StateID id )
     : BaseState( id ) {};

   virtual void OnEntry()
   {
   };

   virtual void OnExit()
   {
   };

   virtual StateID OnEvent( EventType event )
   {
      switch( event )
      {
      }
      return GetSuperState();
   };
}; //}}}
```

Here is a sample file to reproduce the error (highlighting stops after line 460):
[st3-cpp-highlight-bug.cpp](https://gist.github.com/Shirk/8408340)

_Copied from original issue: SublimeTextBugs/Issues#215_

**Comment by TheClams** [comment]
This is fixed in my PR https://github.com/sublimehq/Packages/pull/28

**Comment by wbond** [comment]
This is fixed as of dev build 3110.
