### ISSUE TITLE
javascrypt syntax highlighting problem

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#48]
_From @l1bbcsg on December 24, 2013 6:8_

This particular piece of code is highlighted wrong:
```javascript
goog.json.Serializer.charsToReplace_ = /\uffff/.test("\uffff") ? /[\\\"\x00-\x1f\x7f-\uffff]/g : /[\\\"\x00-\x1f\x7f-\xff]/g;
```

Github gets it right, so you wont see a bug here.
ST however has a quote in second argument of ternary operator (the one regexp that is taken when test is `true`) unterminated causing the rest to be interpreted as a string literal:
 ![st_highlighting_bug](https://f.cloud.github.com/assets/1044684/1804679/f2e06b82-6c60-11e3-9b0a-05a4f4725672.png)
 I'm not quite sure what's the source of the problem, apparently conditional operator is a part of it and it's only this particular combination.

Noticed in ST3 build 3059
The code is apparently from some google base framework library, found here: http://www.ingress.com/jsc/gen_dashboard.js

Edit: I found another similiar issue in the same code, another set of quotes is not terminated here:
```javascript
goog.i18n.DateTimeFormat.TOKENS_ = [/^\'(?:[^\']|\'\')*\'/, /^(?:G+|y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|z+|Z+)/, /^[^\'GyMkSEahKHcLQdmsvzZ]+/];
```

_Copied from original issue: SublimeTextBugs/Issues#201_

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
