### ISSUE TITLE
Hexadecimal double constant isn't highlighted correctly for C

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#49]
_From @x198501131638 on December 5, 2013 3:21_

    0X1.Fp10;

the .Fp10 isn't highlighted the same as 0X1
![screen shot 2013-12-05 at 04 19 01](https://f.cloud.github.com/assets/6053951/1679783/05ce42d2-5d5c-11e3-8b20-7a32e747acce.png)

_Copied from original issue: SublimeTextBugs/Issues#196_

**Comment by wbond** [comment]
This is fixed in dev build 3110.
