### ISSUE TITLE
Add .cmd to "Batch file" Highlights 

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#5]
_From @forcegroup on November 7, 2014 17:25_

The default Batch file '.cmd' is not recognized, it is recommended that increased in Batch File.sublime-package Batch File.tmlanguage filetype cmd

_Copied from original issue: SublimeTextBugs/Issues#558_

**Comment by FichteFoll** [comment]
Added via https://github.com/sublimehq/Packages/pull/9.
