### ISSUE TITLE
Python syntax highlighting error when using raw triple-quote strings

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#50]
_From @rsyring on October 30, 2013 1:25_

Sublime Text 3
Windows Build 3047

If you put this string in a python file:

```python
r'''['''foobar
```

The last triple quote and "foobar" remain string highlighted as well as any text in the file that follows.  The only thing that undoes the highlighting is to close the bracket before the triple quote.

_Copied from original issue: SublimeTextBugs/Issues#179_

**Comment by wbond** [comment]
This was fixed in dev build 3104
