### ISSUE TITLE
Sublime text 3: python bytes syntax highlighting

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#51]
_From @simonzack on October 24, 2013 0:35_

Byte string definitions such as `b''` aren't being highlighted, while unicode string definitions from python 2, such as `u''` are being highlighted properly.

_Copied from original issue: SublimeTextBugs/Issues#176_

**Comment by wbond** [comment]
This is fixed in the latest Python syntax from https://github.com/sublimehq/Packages and will be part of dev build 3112.
