### ISSUE TITLE
Python 3 - Annotations Highlighting Issue

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#53]
_From @Formeo on October 12, 2013 18:47_

In Python 3, [Function Annotations](http://www.python.org/dev/peps/pep-3107/) where introduced, which allow soft type hinting and/or documentation for arguments and return values of functions and methods. They are notated like this: `def foo(arg1: type, arg2: type) -> type:`. However, Sublime Text does not know about them, and messes up its syntax highlighting when a file contains these annotations.

This example shows where Sublime Text fails (just copy-paste it into your editor):
```python
def foo(arg1: int, arg2: bool) -> str:
    pass


def bar(arg1: tuple, arg2: list):
    pass


def baz(arg1, arg2):
    pass
```

With Monokai, it highlights both the argument annotation values and the `pass` keyword  of `bar` orange, while they should be blue and pink, since they are builtins and a keyword respectively. The arguments and the return annotation stay white.
As you can see in `bar`, if you omit the return annotation, `pass` gets highlighted pink correctly, while the arguments still are white, and their annotations still are orange italic.
`baz` has no annotations at all, and gets highlighted correctly.

**System Specs** (although I don't think they have anything to do with it)
Sublime Text 3, Build 3047
OS: Linux 3.8.0
Dist: Kubuntu 13.04
DE: KDE 4.10.5 with Qt 4.8.4

_Copied from original issue: SublimeTextBugs/Issues#166_

**Comment by wbond** [comment]
Support for function annotations was added in https://github.com/sublimehq/Packages/commit/830956cbfc6e925b82131b8431586c7042673a48. It will be part of dev build 3112.
