### ISSUE TITLE
Java grammar doesn't handle template types correctly

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#55]
_From @qgates on October 9, 2013 2:22_

The opening < and closing > are coloured differently. They should both be the same colour, either the colour of the type, or (preferably) the colour of the plain text scope. Haven't looked into a fix for this one, perhaps someone can volunteer :)

Example:

```
List<Camera.Size> previewSizes = currentCameraParameters.getSupportedPreviewSizes();
```

_Copied from original issue: SublimeTextBugs/Issues#161_

**Comment by wbond** [comment]
This was fixed at https://github.com/sublimehq/Packages/tree/master/Java in 2016.
