### ISSUE TITLE
HTML grammar doesn't support quoteless attribute values

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#56]
_From @qgates on October 9, 2013 0:17_

Example:
```
<TD vAlign=top width=180>Blah</TD>
```

Fix (ST2) Edit HTML.tmLanguage, change:
```
865: <string>(?&lt;='|")</string>
```
to:
```
865: <string>(?&lt;==|='|=")</string>
```

_Copied from original issue: SublimeTextBugs/Issues#160_

**Comment by FichteFoll** [comment]
Can not reproduce; probably fixed in 3087.
