### ISSUE TITLE
c++: 'namespace' keyword not highlighted when using namespace alias

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#57]
_From @Barbas on October 6, 2013 15:26_

This will happen when using the format:

namespace new_name = current_name;

This will leave the namespace keyword un-highlighted. Putting a second space between 'namespace' and new_name will make the keyword be highlighted but then the highlighting after the command will be broken.

_Copied from original issue: SublimeTextBugs/Issues#157_

**Comment by wbond** [comment]
This is fixed as of dev build 3110.
