### ISSUE TITLE
CSS number highlighting

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#59]
_From @HeinrichReimer on September 8, 2013 15:24_

CSS numbers are not highlighted properly.
For example ```.5``` is higlighted like CSS classes and ```0.5``` like a number.

_Copied from original issue: SublimeTextBugs/Issues#146_

**Comment by nightpool** [comment]
I can't reproduce this in the latest beta?

this the pattern I see for numbers in CSS:

````XML
<key>captures</key>
<dict>
	<key>1</key>
	<dict>
		<key>name</key>
		<string>keyword.other.unit.css</string>
	</dict>
</dict>
<key>match</key>
<string>(?x)
    (?:-|\+)?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+))
    ((?:px|pt|ch|cm|mm|in|r?em|ex|pc|deg|g?rad|dpi|dpcm|s)\b|%)?
</string>
<key>name</key>
<string>constant.numeric.css</string>
````

**Comment by nightpool** [comment]
(in fact I found this because the SASS package I was using wasn't highlighting leading dots properly, which is a little bit ironic)

**Comment by FichteFoll** [comment]
Can't either, works perfectly well. Most likely fixed with 3087, where the CSS syntax got updated.
