### ISSUE TITLE
Missing function `boolval` from PHP built-in functions list

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#6]
_From @jonahbron on October 31, 2014 16:8_

Most built-in PHP functions that you type are recognized (and autofilled) by the syntax highlighter. For example `strval`, `intval`, etc show up as blue (in the default color scheme).

But the `boolval` function (new as of PHP 5.5) is not autofilled or highlighted differently.

Ubuntu 14.10
SublimeText build 3066
Monokai color scheme

_Copied from original issue: SublimeTextBugs/Issues#544_

**Comment by wbond** [comment]
This is now part of the latest version of the PHP syntax at https://github.com/sublimehq/Packages and will be part of dev build 3112.
