### ISSUE TITLE
Add support for whitesmiths indentation

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#61]
_From @chlab on July 25, 2013 6:52_

As discussed in this [forum thread](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=3252&p=51705&hilit=whitesmith#p51705), it is the opinion of several users and myself that the whitesmiths coding style should be supported by default. 

Whitesmiths style is still used commonly enough for it to be supported by any major editor. In my case, I have no say in this matter, it's the coding style my company has chosen. Day-to-day work with SublimeText is difficult in Whitesmiths when SublimeText enforces a different style.

Example:

    function foo()
      {
        | <- this is where cursor is placed by auto indentation
    | <- clicking an empty line within the function places the cursor here
      | <- but this is where it should be in both cases (for Whitesmiths)
      }

I think an option along the lines of `tab_size_within_structures` would pretty much do the trick. The default would be 0, as it is now. Setting it to 2 in the example above would result in the expected behavior.

References:
- [Whitesmiths Coding style](https://en.wikipedia.org/wiki/Indent_style#Whitesmiths_style)
- [Forum thread discussing this](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=3252&p=51705&hilit=whitesmith#p51705)

_Copied from original issue: SublimeTextBugs/Issues#112_

**Comment by jsiwek** [comment]
Here's a plugin I wrote that attempts to add support for Whitesmiths indent style: https://github.com/jsiwek/WhitesmithsIndentStyle

**Comment by FichteFoll** [comment]
This issue was moved back to the other repo.
