### ISSUE TITLE
Error in C/C++ Syntax

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#63]
_From @schlamar on May 2, 2013 6:38_

Some comments are not recognized in preprocessor statements (first two are fine).

    #if  //comment
    #include //comment

    #warning // no comment
    #error // no comment
    #if
    #endif // no comment
    #if
    #endif /* no comment */

_Copied from original issue: SublimeTextBugs/Issues#30_

**Comment by wbond** [comment]
This was fixed in dev build 3110.
