### ISSUE TITLE
HTML grammar doesnt support escaped quotes

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#64]
_From @fcgrx on May 8, 2013 1:3_

Paste this in a new file and set syntax to HTML:
```<img src="foo" alt='that\'s all folks'>```

You will note that ST does not properly handle the escaped punctuation in the single quotes, and highlighting goes bad

This is the fix:
```
 line 767: <string>(?:[^\\])'</string>

line 731: 	<string>(?:[^\\])"</string>
```

_Copied from original issue: SublimeTextBugs/Issues#40_

**Comment by FichteFoll** [comment]
Browsers don't seem to support this either. I question whether this is actually valid HTML.

Doubling quotes as an escape doesn't seem to work either.

**Comment by wbond** [comment]
Backslash escapes don't exist in HTML. The proper way to handle this is change the surrounding quotes to `"`, or use a named or numeric entity.

http://stackoverflow.com/questions/4015345/how-to-properly-escape-quotes-inside-html-attributes
