### ISSUE TITLE
HTML highlighting fails due to comment problem

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#65]
_From @fcgrx on May 8, 2013 3:23_

Paste this into a new file in ST and set the grammar to HTML:

```
<script>
/* </script> */
</script>
```

Lots of similar problems but this is just a simple test case.

Comments need to override whatever they contain!

_Copied from original issue: SublimeTextBugs/Issues#41_

**Comment by FichteFoll** [comment]
This is actually not a bug. The script tag ends on the first closing tag it encounters. It does not matter what preceded the closing tag and whether that could cause the tag to be inside a comment of some arbitrary language.

For this and other reasons you externalize your javascript files.
