### ISSUE TITLE
updates for Clojure.sublime-package - upstream source?

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#66]
_From @trevor on May 24, 2013 5:31_

Clojure.sublime-package (aka Clojure.tmLanguage) is in need of updating with Clojure 1.5, where can those be submitted for inclusion in ST3?

_Copied from original issue: SublimeTextBugs/Issues#50_

**Comment by keith-hall** [comment]
You can make PRs to https://github.com/sublimehq/Packages/tree/master/Clojure if you wish to improve the Clojure syntax highlighting in ST.
