### ISSUE TITLE
Solarized colour scheme inconsistence

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#67]
_From @fuadsaud on June 2, 2013 11:43_

The Sublime Text default version of the Solarized colour scheme (both dark and light versions) is pretty inconsistent with the Solarized definition (http://ethanschoonover.com/solarized#features).

There's a third party package (https://github.com/SublimeColors/Solarized) which solves the problem partially (it's still a little different from the original one), but the default one should comply with the standard (else it should not be called Solarized, I think).

_Copied from original issue: SublimeTextBugs/Issues#56_

**Comment by FichteFoll** [comment]
This issue has been moved back to the other repo.
