### ISSUE TITLE
C/C++ Syntax: Multiple parameters in #define preprocessor

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#68]
_From @FichteFoll on June 24, 2013 2:21_

```c
#define sign(a) (((a) > 0) - ((a) < 0))
```
renders the first `a` just fine as `source.c meta.preprocessor.macro.c variable.parameter.preprocessor.c` and is highlighted as variable in most color schemes.

However:
```c
#define sign(a, b) (((a) > (b)) - ((a) < (b)))
```
is not highlighted as above and only renders as `source.c meta.preprocessor.macro.c 
`.

Forum source: http://www.sublimetext.com/forum/viewtopic.php?p=50151#p50151

_Copied from original issue: SublimeTextBugs/Issues#71_

**Comment by wbond** [comment]
This was fixed in dev build 3110.
