### ISSUE TITLE
No auto indentation after <tags>

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#69]
_From @FichteFoll on July 1, 2013 13:3_

Reported on [#sublimetext](irc:://irc.freenode.net/sublimetext) (and confirmed on ST 3046):

``` html
<!-- Note: pretend `|` is the cursor -->
<!-- ST2 -->
<div>[enter]
        |
        ^--- Cursor indented on next line


<!-- ST3 -->
<div>[enter]
|
^--- Cursor *not* indented
```

Expected: the new line should be indented like in ST2.

_Copied from original issue: SublimeTextBugs/Issues#81_

**Comment by keith-hall** [comment]
https://github.com/guillermooo/sublime-undocs/issues/217#issuecomment-231712504

**Comment by keith-hall** [comment]
fixed by https://github.com/sublimehq/Packages/pull/841
