### ISSUE TITLE
#define quote mismatch

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#73]
_From @TheBiggerGuy on December 2, 2013 14:42_

Quotes in a `#define` block are mismatched and thus further highlights are missing.

_Expected_
```C
#define A B(C) ";" \
  "a, "            \
  "b = " D ", "    \
  "c = " E ", "    \
  "d = " F

void func_a() {
  int a;
  a = a + 1;
}
```
_Actual_
![sublime_define_issue](https://f.cloud.github.com/assets/152316/1655256/141a83e0-5b5f-11e3-87ad-4461ed291c48.png)

_Copied from original issue: SublimeTextBugs/Issues#195_

**Comment by wbond** [comment]
This was fixed as of dev build 3110.
