### ISSUE TITLE
Markdown not highlighted with default color scheme

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#75]
_From @loicdescotte on July 17, 2013 14:13_

Hi,
I live Monokai and markdown, unfortunatly there is no markdown support with this color scheme.
It seems that it's still not working with SublimeText3

_Copied from original issue: SublimeTextBugs/Issues#104_

**Comment by keith-hall** [comment]
The Monokai color scheme that ships with build 3127 now includes colors for Markdown.
