### ISSUE TITLE
Symbol indexing fails for C function declarations

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#76]
_From @nickhutchinson on February 26, 2014 22:11_

Sublime Text 3 fails to index C function declarations/definitions of the following form:

~~~c
void func_name0
    (int foo,
     int bar
    );
~~~

The following, however, does work:

~~~c
void func_name1(
     int foo,
     int bar
    );
~~~

Separating the opening paren from the function name might be weird, but unfortunately it's all over our codebase, and makes the symbol indexing feature much less useful than it could be.

_Copied from original issue: SublimeTextBugs/Issues#250_

**Comment by wbond** [comment]
This was fixed in dev build 3110.
