### ISSUE TITLE
HTML autocompletion does not respect self-closing <tags />

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#77]
_From @FichteFoll on June 30, 2013 22:49_

Reported by @geometryone (in #45):
> now other tags close unexpected
> 
>     <node />
>     <node /></
>
> becomes `<node /></node>`
> 
> same applies to
> 
>     <tag>
>     <node />
>     </
>
> will close with `</node>`

ST 3046.

Apparently, `close_tag` seems to be an internal command (not defined anywhere) so I can't go ahead and do that myself.

_Copied from original issue: SublimeTextBugs/Issues#79_

**Comment by FichteFoll** [comment]
As I was labelling the moved issues I noticed that this issue is not actually one with the default packages since, as mentioned above, `close_tag` is not defined in any Python file.

I propose to close this issue and re-open the original.

**Comment by titoBouzout** [comment]
I propose to open a new issue to "open source" that command. It has tons of exeptions. Not cool having lots of duplicates reporting similar things.

**Comment by FichteFoll** [comment]
You could as well open an issue to "open source" the entirety of ST then.

**Comment by titoBouzout** [comment]
yes why not

**Comment by FichteFoll** [comment]
Anyway, I'm closing this. Continue discussion in https://github.com/SublimeTextIssues/Core/issues/79.
