### ISSUE TITLE
HTML autocompletion closes <script> tags twice

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#78]
_From @FichteFoll on May 16, 2013 11:40_

When typing `</` to close the most recently opened script tag it will close it correctly. However, it seems that the tag is not closed internally as typing `</` again will close another non-existant script tag.

**Steps to reproduce:**
1. Open a new view
2. Set the Syntax to HTML
3. Insert the following snippet (see minimal example below in video, this is just demonstration):
```html
<html> 
    <script>
    <!--
        var lol = "test <p> </p>"
    -->
    </script>
    dasdsad
    <p> </p>
    
```
4. Type`</` at the end

**Expected behavior:**
- It should autocomplete to `</html>`.

**Actual behavior:**
- Autocompletes to `</script>`

Here is a screencast demonstrating the issue: http://img.iamntz.com/jing/video_98.mp4

This was probably introduced with the recent changes for Build 3034 but I don't have 3032 here right now so I can't test if this is a regression.

Reported: http://www.sublimetext.com/forum/viewtopic.php?f=2&t=12397#p48600

_Copied from original issue: SublimeTextBugs/Issues#45_

**Comment by FichteFoll** [comment]
I can not reproduce this for valid tags in HTML (i.e. not `<node />`) and can not in XML either. Please comment if this is wrong.

**Comment by geometryone** [comment]
In the editor in syntax HTML the same applies to any other tag.

<template>
	<price />
	<tag></tag>
when you type </ it will close with </price> which is wrong imo.

**Comment by FichteFoll** [comment]
Yes, that is true. It works for all common HTML tags but it does not if you use it on seemingly arbitrary tags. I'm not exactly involved in webdev, I think that some weird HTML flavors exist where these arbitrary tags are valid and interpreted in some way. Thus I believe you are right in thinking the current behavior is still wrong (and inconsistent).

**Comment by wbond** [comment]
We should rename this issue if it is now about auto-completing closing tags for self-closed tags.

**Comment by FichteFoll** [comment]
Better yet, I created a new issue, which is more clean. Issues mentioned in comments are bound to be confusing when the initial issue in the OP is fixed already.

#176
