### ISSUE TITLE
Wrong coloring for named class members

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#80]
_From @caiotoon on December 18, 2014 16:50_

I'm not sure if this is an issue on Sublime syntax recognition or on the theme itself. Pretty much, when you're declaring a Javascript class and you create a member on the `this` element it gets colored as a `function`, what makes a lot of sense IMO. If you name the function this stops working though.

Pretty much, this gets colored correctly:

```javascript
this.something = function() {
};
```

but this does not get proper colored:

```javascript
this.something = function nameForAnonymousFunction() {
};
```

Same behavior as GitHub syntax coloring right now. I wonder if this is indeed a bug, if not, do you guys mind explaining me the reason for this difference?

_Copied from original issue: SublimeTextBugs/Issues#610_

**Comment by caiotoon** [comment]
Hi there.

I've just submitted this [PR}(https://github.com/atom/language-javascript/pull/125) to fix the same issue for Github and Atom.io. I was wondering whether you're using any open source solution for the grammar. Maybe I could try a PR there to speed up this fix.

Cheers.

**Comment by FichteFoll** [comment]
Hi, @caiotoon, thanks for the reference. Unfortunately the sources for the default packages have not been "opened" by the Sublime Text developer. There have been ideas by the community to take over this process which you can read [here](https://github.com/SublimeTextIssues/Core/issues/621), but to my knowledge no actual work has been done.

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
