### ISSUE TITLE
Scala syntax highlighter doesn't recognize that the triple-quote has ended in ST3

### ISSUE THREAD

**Issue by tsuyoshizawa** [SublimeTextIssues/DefaultPackages#82]
Scala supports triple-quotes syntax and embedding double-quotes into there.

```
def s = """a="b""""
```

However, ST's syntax highlighter doesn't recognize that the triple-quote has ended.

- Operating System:
    - Mac OS X (10.10.1)
- The version of Sublime Text that you're using:
    - Build 3065
- Any related software which may cause ST to act strangely:
    - Nothing

I could find a same problem about ST2 in user forum.

http://www.sublimetext.com/forum/viewtopic.php?f=3&t=2707&start=0&sid=2cf9fb6727030f53a713c41d3668d394

I confirmed that this problem is resolved by modifying the file in ST3.

**Comment by jrappen** [comment]
Cannot reproduce with Build 3111 on Win x64.
