### ISSUE TITLE
Sequences of CSS Attribute Selectors in *.css Files Do Not Highlight Correctly

### ISSUE THREAD

**Issue by patrickdark** [SublimeTextIssues/DefaultPackages#83]
Consider these CSS selectors in Sublime Text 3 Build 3065 using the Monokai theme:

```CSS
[class~="1"][class~="2"][class~="3"] {}
[class~="a"] {}
```

In the first line, containing three attribute selectors, the first attribute selector is not highlighted and all characters appear in the default color (white). The correct colors are shown in subsequent attribute selectors.

As demonstrated by the second line, when the first attribute selector contains certain values, such as `a`, that value will receive a highlight, though in the wrong color (pink).

**Comment by wbond** [comment]
This is fixed with the latest CSS syntax from https://github.com/sublimehq/Packages, which will be part of dev build 3112.
