### ISSUE TITLE
Element Names with Period Characters in *.xml, *.xhtml, and *.html Files Are Not Highlighted Correctly

### ISSUE THREAD

**Issue by patrickdark** [SublimeTextIssues/DefaultPackages#85]
Consider this XML document in Sublime Text 3 Build 3065 using the Monokai theme:

```XML
<document>
	<element.name></element.name>
</document>
```

The `element.name` element is not highlighted correctly at and after the period character (i.e., for the part reading `.name`). Those parts of the name appear in the default color (white) instead of pink. (Note that most characters are valid in XML element names.)

Note that a similar issue exists for HTML and XHTML documents even though this structure is not valid in such documents: the `.name` portion of the element name appears in green instead of pink. 

```XHTML
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Demo</title>
	</head>
	<body>
		<element.name xmlns=""></element.name>
	</body>
</html>
```

This looks better than white, but is still wrong based on the following code using hyphen-minus characters as separators which show the element names entirely in pink:

```XML
<document>
	<element-name></element-name>
</document>
```

```XHTML
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Demo</title>
	</head>
	<body>
		<element-name xmlns=""></element-name>
	</body>
</html>
```

**Comment by keith-hall** [comment]
I believe this has just been fixed in this commit: https://github.com/sublimehq/Packages/commit/fe943080e895bfbeedd5f6277dbacef33474b7ab
