### ISSUE TITLE
"title_case" command leaves some words unchanged

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#87]
_From @canoeberry on December 21, 2014 14:3_

If I highlight the following code:

    cursor = function(regions[i], *args, **kwargs)

and execute the title_case command, I get this:

    Cursor = Function(regions[i], *args, **kwargs)

As you can see, "regions", "i", "args" and "kwargs" were not touched, because the characters in front were ... punctuation or something? Not sure, but it is wrong in my opinion.

If I run the upper_case command instead, I get this:

    CURSOR = FUNCTION(REGIONS[I], *ARGS, **KWARGS)

as expected.

_Copied from original issue: SublimeTextIssues/Core#613_

**Comment by canoeberry** [comment]
I implemented a work-around by copying the text out of the buffer with view.substr(...) and then calling text.title() on the result and splicing it back in. It's not too bad.

**Comment by FichteFoll** [comment]
This issue was moved back to the other repo.
