### ISSUE TITLE
"save_on_focus_lost" and Read-Only files

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#88]
_From @esmirnov on December 10, 2014 9:6_

Platform Windows:

1) Enable "save_on_focus_lost"
2) Opend read-only file
3) Edit
4) Switch to other window

Now you will see "Access denied" and "Overwrite read-only file?" dialogs in a loop. Very hard to cancel this dialogs.

_Copied from original issue: SublimeTextIssues/Core#601_

**Comment by FichteFoll** [comment]
This is a core issue.

**Comment by titoBouzout** [comment]
mmmh I don't think so, but maybe I'm missing something, the relevant file is 
/Default/save_on_focus_lost.py

**Comment by FichteFoll** [comment]
Ah okay, I didn't know this was implemented as a plugin (and couldn't check).

**Comment by FichteFoll** [comment]
Merged this issue into https://github.com/SublimeTextIssues/Core/issues/980.
