### ISSUE TITLE
PHP UTF-8 Variable Names & Syntax Highlighting

### ISSUE THREAD

**Issue by Dygear** [SublimeTextIssues/DefaultPackages#89]
**OS and OS version:**
Windows 7 & Mac OSX 10.10 (Yosemite)

**Sublime Text Version:**
3065

**Did you tried to revert to a freshly installed state?**
No.

**Bug Description:**
UTF-8 variable names __are__ valid within UTF-8 encoded documents for PHP, but the current syntax highlighter does not pick up on this.

**How to reproduce:**

	<?php

		// ASCII Works
		$d = 0;
		echo "$d {$d} ${d}";

		// UTF-8 Does Not
		$Δ = 0;
		echo "$Δ {$Δ} ${Δ}";

	?>

![simpletext php utf-8 highlighting](https://cloud.githubusercontent.com/assets/367860/5610538/2c25e814-9487-11e4-9305-4ccdee1b16c6.gif)

**Comment by FichteFoll** [comment]
Same for Python function/class definitions btw.

**Comment by FichteFoll** [comment]
Oniguruma supports unicode afaik (there are sets for it). [SyntaxHighlightTools](https://sublime.wbond.net/packages/SyntaxHighlightTools) provides a way to substitute reccuring expressions in language definitions. I haven't actually used it as of now (too busy with other stuff) but it might be worth giving it a shot. A converter from conventional definitions might be necessary though.

**Comment by wbond** [comment]
The latest version of the PHP syntax from https://github.com/sublimehq/Packages supports unicode variable names. It will be part of dev build 3112.
