### ISSUE TITLE
border-?-?-radius not highlighted correctly in CSS

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#9]
_From @genr8r on October 3, 2014 19:25_

There appears to be an issue in using border-bottom-radius-right and border-bottom-radius-left.  The css does not highlight correctly in ST3 and it is not rendering in the browser after the css is saved.

Using a clean version of ST3 (build 3065) with no plugins or tweaks
Mac OSX 10.9.5
FF 33.0 (beta9)

_Copied from original issue: SublimeTextBugs/Issues#509_

**Comment by FichteFoll** [comment]
Fixed in 3104, probably earlier around 3087 though.
