### ISSUE TITLE
Symbol indexer ignores typedefs

### ISSUE THREAD

**Issue by FlorianZ** [SublimeTextIssues/DefaultPackages#90]
Consider the following code snippet:
``` CPP
typedef int foo;
struct bar {};

foo a;
bar b;
```
ST3 correctly indexes ```bar``` but fails to do so for ```foo```. IMHO, it would be useful to have ```typedef```s indexed as well, or at least have an option. Thanks!

**Comment by wbond** [comment]
This was fixed in dev build 3110.
