### ISSUE TITLE
JavaScript syntax highlighting breaks in .asp files after for loop (no spaces in condition expression)

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#91]
_From @apuchkov on January 15, 2015 22:4_

OS and OS version: Windows 8.1 Pro
Sublime Text Version: 3065
Did you tried to revert to a freshly installed state? No

The problem is broken JavaScript syntax after for loop in .asp files. It happens only:
 - in .asp files (.js files don't have this problem)
 - when no spaces in condition expression

**Example of the problem:**
![Broken highlight](http://content.screencast.com/users/derimer/folders/Jing/media/19ec6006-97eb-4b25-8e5e-b89f01f7ac04/2015-01-15_1657.png)

**Example of correct syntax highlight**
![Correct syntax highlight](http://content.screencast.com/users/derimer/folders/Jing/media/4ae57c27-dba4-4d8a-baf3-29242306b890/2015-01-15_1657.png)

**Code to reproduce the problem:**

    <html>
    <head>
    	<script type="text/javascript">
    		function foo() {
    			for (i=0; i<10; i++) {
    			}
    			var bar = 0;
    		}
    	</script>
    </head>
    </html>

_Copied from original issue: SublimeTextIssues/Core#642_

**Comment by wbond** [comment]
This was fixed sometime before on with dev build 3110.
