### ISSUE TITLE
Sublime won't let me save a new file sometimes.

### ISSUE THREAD

**Issue by Brian-G-1206** [SublimeTextIssues/DefaultPackages#92]
I've narrowed this behavior down to any new file that has a \x14 character on the first line. I haven't found any other characters that cause this problem.

**Comment by titoBouzout** [comment]
check setting to false in your preferences the following:

set_unsaved_view_name
save_on_focus_lost

**Comment by FichteFoll** [comment]
This issue was moved to SublimeTextIssues/Core#649
