### ISSUE TITLE
Highlighting bug when space between attribute and equal sign

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#93]
_From @azhidkov on January 21, 2015 12:34_

If space between attribute and equal sign attribute do not become green. Screenshot attached.
![sublime_highlitgting_error](https://cloud.githubusercontent.com/assets/3435397/5836179/efd6762c-a182-11e4-8b16-133748cb9be8.png)

_Copied from original issue: SublimeTextIssues/Core#647_

**Comment by FichteFoll** [comment]
I'm not exactly sure if this is valid HTML/XML. Can you verify?

**Comment by azhidkov** [comment]
Yes, I'm working in Visual Studio and it successfully parsed this config file and run my program properly.

**Comment by azhidkov** [comment]
And I've checked this xml with http://www.w3schools.com/xml/xml_validator.asp validator and it showed me "No errors found" message.

**Comment by FichteFoll** [comment]
Fixed in HTML, still broken in XML.
