### ISSUE TITLE
Open URL doesn't know its limits!

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#98]
_From @iamntz on January 31, 2015 15:31_

In 3067 build, there is this new feature

> Right clicking on a URL will show an 'Open URL' menu item

The problem is that it doesn't really know when an URL is finished (i guess the regex is too greedy), because if you have a json object full of links,

```
[
  "http://foo.bar",
  "http://foo.baz"
]
```

Right clicking will open `http://foo.bar",`

### The fix

On `open_context_url.py` (from the default packages), we have this regex:

    it = re.finditer(r"\bhttp(s)?://[^ \t]+", text)

Which obviously, it's kind of wrong. I tested a bit and this works better:

    it = re.finditer(r"\b[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{1,}\.[a-z]{2,}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)", text)

_Copied from original issue: SublimeTextIssues/Core#654_

**Comment by iamntz** [comment]
Oh dear, I was thinking that Core means.. well, core of sublime, where also default packages goes. 

I was wrong, next time i'll try to rtfm :dash: 

Thanks!

**Comment by iamntz** [comment]
Closed with last build.

**Comment by facelessuser** [comment]
I personally would not close this as the regex still grabs things like periods and things.

So if I have this sentence http://someurl.com/whatever.  You will notice that github does not include the period in this comment.  Sublime still does.

I posted a regex on the forum which I have cleaned up for here which does not suffer from this problem.  Maybe someone has better, I don't know, but I will leave it here:

```python
rex = re.compile(
    r'''(?x)(?i)
    (?:
        (?:
            https?://(?:(?:[a-z\d\-._]+(?:\.[a-z\d\-._]+)+)|localhost)|  # http://
            w{3}\.[a-z\d\-._]+(?:\.[a-z\d\-._]+)+                        # www.
        )
        /?[a-z\d\-._?,'/+&%$#]*[a-z\d\-._?,'/+&%=:"|~;]*                 # querry stuff
        [a-z\d\-_~:/?#@!$*+=]                                            # allowed end chars
    )
    '''
)
```

**Comment by facelessuser** [comment]
Updated regex to no include question marks or exclamation marks at end of url.

**Comment by facelessuser** [comment]
Added a little bit more refinement and added support for a couple more things.

**Comment by FichteFoll** [comment]
The current regex used in 3070 is now equivalent to the one mentioned above by @facelessuser, except for the case insensivity flag which is not included. I don't have specific issues with that as I rarely if ever saw an all-caps url.
